import { ChangeEvent, ReactNode, useEffect, useState } from 'react';
import { ArrowLeft, Beaker, DatabaseBackup, Gauge, ShieldCheck, Trophy } from 'lucide-react';
import { buildCausalPrescriptionEvidence } from '../../learning-engine/causalPrescription';
import { validateExploitCandidate } from '../../learning-engine/exploitValidation';
import { evaluateLearningExperiment, LearningExperimentSpec } from '../../learning-engine/experiment';
import { buildLongitudinalPokerReport } from '../../learning-engine/longitudinal';
import { evaluatePopulationDeviation, PopulationDeviationInput } from '../../learning-engine/populationInference';
import { evaluateTournamentRangeEvidence, TournamentRangeEvidence } from '../../real-game/tournamentDecisionEvidence';
import { blobLines, exportTruthWorkspaceLines, importTruthWorkspaceLines, streamTruthWorkspaceToWritable } from '../../solver-data/truthWorkspace';
import { STRATEGY_PROFILES_V2, StrategyProfile, TruthCoverageTargetEnvelope, buildUnifiedTruthCoverage } from '../../strategy-engine-v2';
import { getPostflopTruthStore } from '../../strategy-engine-v3';
import { getMultiwayTruthStore, importMultiwayTruthNdjson } from '../../strategy-engine-v4';
import { loadHistory } from '../../utils/history';

function customProfiles():StrategyProfile[]{try{const parsed=JSON.parse(localStorage.getItem('poker_strategy_profiles_v2')||'[]');return Array.isArray(parsed)?parsed:[];}catch{return[];}}
function activeExperiment():LearningExperimentSpec|undefined{try{const parsed=JSON.parse(localStorage.getItem('poker_learning_experiment_v1')||'null');return parsed&&typeof parsed==='object'?parsed as LearningExperimentSpec:undefined;}catch{return undefined;}}

type SavePickerWindow=Window&{showSaveFilePicker?: (options?:unknown)=>Promise<{createWritable:()=>Promise<WritableStream<Uint8Array>>}>};

export function EvidenceOpsDashboard({onExit}:{onExit:()=>void}){
 const v3=getPostflopTruthStore(),v4=getMultiwayTruthStore();
 const [status,setStatus]=useState('');const [coverage,setCoverage]=useState<{contexts:number;combos:number;fullEv:number;ambiguous:number;target?:number}>({contexts:0,combos:0,fullEv:0,ambiguous:0});
 const [targetJson,setTargetJson]=useState('');const [rangeJson,setRangeJson]=useState('');const [rangeResult,setRangeResult]=useState('');const [exploitJson,setExploitJson]=useState('');const [exploitResult,setExploitResult]=useState('');const [causalTargetJson,setCausalTargetJson]=useState('');const [causalResult,setCausalResult]=useState('');const [v4Meta,setV4Meta]=useState({packId:'multiway-stream',version:'1',sourceReference:'file://multiway-export'});
 const refreshCoverage=async(target?:TruthCoverageTargetEnvelope)=>{const report=await buildUnifiedTruthCoverage([...STRATEGY_PROFILES_V2,...customProfiles()],v3,v4,target);setCoverage({contexts:report.totals.uniqueContexts,combos:report.totals.uniqueCombos,fullEv:report.totals.fullEvCombos,ambiguous:report.totals.ambiguousCombos,target:report.weightedTargetCoverage});};
 useEffect(()=>{void refreshCoverage();},[]);
 const evaluateTargets=async()=>{try{const envelope=targetJson.trim()?JSON.parse(targetJson) as TruthCoverageTargetEnvelope:undefined;await refreshCoverage(envelope);setStatus(envelope?'P19 target coverage recomputed from actual unique truth.':'P19 portfolio refreshed.');}catch(error){setStatus(error instanceof Error?error.message:'Coverage failed.');}};
 const evaluateRange=()=>{try{const result=evaluateTournamentRangeEvidence(JSON.parse(rangeJson) as TournamentRangeEvidence);setRangeResult(JSON.stringify(result,null,2));setStatus(`P20 tournament range: ${result.status} · ${result.method}.`);}catch(error){setStatus(error instanceof Error?error.message:'Range evidence failed.');}};
 const evaluateExploit=()=>{try{const envelope=JSON.parse(exploitJson) as {deviation:PopulationDeviationInput;candidateProfileKey:string;holdout:Parameters<typeof validateExploitCandidate>[0]};const candidate=customProfiles().find(profile=>`${profile.id}@${profile.version}`===envelope.candidateProfileKey)||STRATEGY_PROFILES_V2.find(profile=>`${profile.id}@${profile.version}`===envelope.candidateProfileKey);if(!candidate)throw new Error('P21 candidate profile not found in Strategy Profile v2 registry.');const deviation=evaluatePopulationDeviation(envelope.deviation);const result=validateExploitCandidate(envelope.holdout,deviation,candidate);setExploitResult(JSON.stringify(result,null,2));setStatus(`P21 exploit candidate: ${result.status}.`);}catch(error){setStatus(error instanceof Error?error.message:'Exploit validation failed.');}};
 const evaluateCausal=()=>{try{const spec=activeExperiment();if(!spec)throw new Error('No active P10 experiment is stored.');const result=evaluateLearningExperiment(loadHistory(),spec),target=JSON.parse(causalTargetJson) as Parameters<typeof buildCausalPrescriptionEvidence>[2],evidence=buildCausalPrescriptionEvidence(spec,result,target);const prescriptions=buildLongitudinalPokerReport(loadHistory()).prescriptions;const matching=evidence?prescriptions.find(item=>item.decisionFamilyId===evidence.targetDecisionFamilyId):undefined;setCausalResult(JSON.stringify({experimentResult:result,evidence,matchingPrescription:matching},null,2));setStatus(evidence?'P22 randomized intervention evidence linked to its preregistered decision family.':'P22 experiment is insufficient or has no winning arm; no intervention was linked.');}catch(error){setStatus(error instanceof Error?error.message:'Causal linkage failed.');}};
 const importV4Ndjson=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const result=await importMultiwayTruthNdjson(blobLines(file),v4,v4Meta);await refreshCoverage();setStatus(`P18-E v4 stream imported ${result.imported}, skipped ${result.skipped}.`);}catch(error){setStatus(error instanceof Error?error.message:'v4 stream import failed.');}event.currentTarget.value='';};
 const exportWorkspace=async()=>{try{const picker=(window as SavePickerWindow).showSaveFilePicker;if(picker){const handle=await picker({suggestedName:'poker-truth-workspace.ndjson',types:[{description:'NDJSON',accept:{'application/x-ndjson':['.ndjson']}}]}),writable=await handle.createWritable();await streamTruthWorkspaceToWritable(v3,v4,writable);setStatus('P23 workspace streamed to file without materializing the full truth database.');return;}const lines:string[]=[];for await(const line of exportTruthWorkspaceLines(v3,v4))lines.push(line);const url=URL.createObjectURL(new Blob([`${lines.join('\n')}\n`],{type:'application/x-ndjson'})),anchor=document.createElement('a');anchor.href=url;anchor.download='poker-truth-workspace.ndjson';anchor.click();URL.revokeObjectURL(url);setStatus('P23 workspace exported with Blob fallback; File System Access is preferred for very large stores.');}catch(error){setStatus(error instanceof Error?error.message:'Workspace export failed.');}};
 const importWorkspace=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{await importTruthWorkspaceLines(blobLines(file),v3,v4,{validateOnly:true});const result=await importTruthWorkspaceLines(blobLines(file),v3,v4);await refreshCoverage();setStatus(`P23 workspace ${result.workspaceId}: restored v3=${result.v3Nodes}, v4=${result.v4Nodes}; immutable skips ${result.skippedV3+result.skippedV4}.`);}catch(error){setStatus(error instanceof Error?error.message:'Workspace import failed.');}event.currentTarget.value='';};
 return <div data-testid="evidence-ops-dashboard" className="min-h-screen bg-slate-950 px-4 py-6 text-slate-100 md:px-8"><div className="mx-auto max-w-7xl"><button onClick={onExit} className="flex items-center gap-2 rounded-xl border border-slate-800 px-4 py-2 text-sm"><ArrowLeft className="h-4 w-4"/>返回</button>
  <section className="mt-6 rounded-3xl border border-emerald-500/20 bg-emerald-500/5 p-6"><div className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-300">P18 → P23 · evidence operations</div><h1 className="mt-3 text-3xl font-bold">Real-world Geometry、Truth Coverage、Tournament Evidence、Exploit Validation、Causal Coach、Portable Workspace</h1><p className="mt-3 max-w-5xl text-sm leading-7 text-slate-300">這一層只把能證明的狀態升級。特殊 HH geometry 必須進 exact key；simulation 不冒充 exact math；population deviation 不自動生成 exploit；observational leak 與 randomized intervention evidence 分離。</p></section>
  <section className="mt-5 grid gap-3 md:grid-cols-4"><Metric label="P19 exact contexts" value={coverage.contexts}/><Metric label="unique usable combos" value={coverage.combos}/><Metric label="full-EV combos" value={coverage.fullEv}/><Metric label="ambiguous combos" value={coverage.ambiguous}/></section>
  <section className="mt-6 grid gap-5 xl:grid-cols-2">
   <Panel icon={<Gauge className="h-5 w-5"/>} title="P19 · Real Truth Coverage"><p>只有唯一 verified node 的 combo 才算 usable；重疊版本算 ambiguous。可另貼 versioned target envelope 計算 weighted coverage。</p><textarea data-testid="p19-target-json" value={targetJson} onChange={event=>setTargetJson(event.target.value)} placeholder="TruthCoverageTargetEnvelope JSON (optional)" className="mt-3 min-h-36 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p19-evaluate" onClick={()=>void evaluateTargets()} className="mt-2 rounded-lg bg-emerald-400 px-3 py-2 text-xs font-bold text-emerald-950">Recompute coverage</button>{coverage.target!==undefined&&<div className="mt-2 text-sm text-emerald-200">Weighted target coverage {(coverage.target*100).toFixed(1)}%</div>}</Panel>
   <Panel icon={<Trophy className="h-5 w-5"/>} title="P20 · Tournament Range Evidence"><p>Range + exact cards/board + provenance 可重算 equity；exact enumeration 才能進 exact ICM/PKO。Monte Carlo 只標 simulation-only。</p><textarea data-testid="p20-range-json" value={rangeJson} onChange={event=>setRangeJson(event.target.value)} placeholder="TournamentRangeEvidence JSON" className="mt-3 min-h-36 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p20-evaluate" onClick={evaluateRange} className="mt-2 rounded-lg bg-amber-400 px-3 py-2 text-xs font-bold text-amber-950">Evaluate range evidence</button>{rangeResult&&<pre className="mt-3 max-h-48 overflow-auto rounded-xl bg-slate-950 p-3 text-[11px]">{rangeResult}</pre>}</Panel>
   <Panel icon={<ShieldCheck className="h-5 w-5"/>} title="P21 · Exploit Holdout Validation"><p>P16 deviation + external population-exploit candidate + independent paired EV holdout。策略不是由偏差自動合成。</p><textarea data-testid="p21-exploit-json" value={exploitJson} onChange={event=>setExploitJson(event.target.value)} placeholder='{"deviation":{...},"candidateProfileKey":"population:...@1","holdout":{...}}' className="mt-3 min-h-40 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p21-evaluate" onClick={evaluateExploit} className="mt-2 rounded-lg bg-cyan-400 px-3 py-2 text-xs font-bold text-cyan-950">Validate exploit candidate</button>{exploitResult&&<pre className="mt-3 max-h-48 overflow-auto rounded-xl bg-slate-950 p-3 text-[11px]">{exploitResult}</pre>}</Panel>
   <Panel icon={<Beaker className="h-5 w-5"/>} title="P22 · P10 ↔ P17 Causal Coach"><p>Target 必須在 experiment preregistration 前登記。只有 randomized-n-of-1 通過後，才把 winning intervention 掛到對應 leak family。</p><textarea data-testid="p22-target-json" value={causalTargetJson} onChange={event=>setCausalTargetJson(event.target.value)} placeholder="PreregisteredExperimentTarget JSON" className="mt-3 min-h-40 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p22-evaluate" onClick={evaluateCausal} className="mt-2 rounded-lg bg-fuchsia-400 px-3 py-2 text-xs font-bold text-fuchsia-950">Link randomized evidence</button>{causalResult&&<pre className="mt-3 max-h-48 overflow-auto rounded-xl bg-slate-950 p-3 text-[11px]">{causalResult}</pre>}</Panel>
   <Panel icon={<DatabaseBackup className="h-5 w-5"/>} title="P18-E / P23 · Multiway Stream + Portable Truth"><p>v4 NDJSON 逐行進 IndexedDB，pack manifest 保留真 counts/bytes。Workspace 先完整 validate 一趟，再 additive immutable restore；不會清空現有 truth。</p><div className="mt-3 grid grid-cols-3 gap-2"><input value={v4Meta.packId} onChange={event=>setV4Meta({...v4Meta,packId:event.target.value})} className="rounded-lg bg-slate-950 p-2 text-xs"/><input value={v4Meta.version} onChange={event=>setV4Meta({...v4Meta,version:event.target.value})} className="rounded-lg bg-slate-950 p-2 text-xs"/><input value={v4Meta.sourceReference} onChange={event=>setV4Meta({...v4Meta,sourceReference:event.target.value})} className="rounded-lg bg-slate-950 p-2 text-xs"/></div><label className="mt-3 block text-xs">Import v4 NDJSON<input data-testid="p18-v4-ndjson" type="file" accept=".ndjson,.jsonl,text/plain" onChange={importV4Ndjson} className="mt-1 block w-full"/></label><div className="mt-4 flex flex-wrap gap-2"><button data-testid="p23-export" onClick={()=>void exportWorkspace()} className="rounded-lg bg-blue-400 px-3 py-2 text-xs font-bold text-blue-950">Export truth workspace</button><label className="rounded-lg border border-blue-400/30 px-3 py-2 text-xs text-blue-200">Validate + restore<input data-testid="p23-import" type="file" accept=".ndjson,text/plain" onChange={importWorkspace} className="hidden"/></label></div></Panel>
  </section>{status&&<div data-testid="evidence-ops-status" className="mt-5 rounded-xl border border-emerald-500/20 bg-emerald-500/6 px-4 py-3 text-sm text-emerald-100">{status}</div>}
 </div></div>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-slate-800 bg-slate-900/55 p-3"><div className="text-[11px] text-slate-500">{label}</div><div className="mt-1 break-words font-mono font-bold">{value}</div></div>}
function Panel({icon,title,children}:{icon:ReactNode;title:string;children:ReactNode}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5 text-xs leading-6 text-slate-400"><div className="flex items-center gap-2 text-base font-semibold text-slate-100">{icon}{title}</div><div className="mt-3">{children}</div></div>}
