import { useEffect, useState } from 'react';
import { ArrowLeft, Database, ShieldCheck, Trophy } from 'lucide-react';
import { PostflopTruthPackV3, getPostflopTruthStore, migrateLegacyPostflopTruthStorage } from '../../strategy-engine-v3';
import { importTournamentMetadataEnvelope } from '../../real-game/tournamentReconstruction';
import { loadObservedPopulationCohorts, loadTournamentMetadata, saveTournamentMetadata } from '../../real-game/p12Storage';

export function PostflopTruthLab({onExit}:{onExit:()=>void}){
 const store=getPostflopTruthStore();const [solverJson,setSolverJson]=useState(''),[tournamentJson,setTournamentJson]=useState(''),[message,setMessage]=useState(''),[tournamentCount,setTournamentCount]=useState(()=>loadTournamentMetadata().length);const [diag,setDiag]=useState({backend:store.backend,nodes:0,contexts:0,packs:0,approximateBytes:0});const cohorts=loadObservedPopulationCohorts();
 const refresh=async()=>setDiag(await store.diagnostics());useEffect(()=>{void(async()=>{await migrateLegacyPostflopTruthStorage(store);await refresh();})();},[]);
 const importSolver=async()=>{try{const pack=JSON.parse(solverJson) as PostflopTruthPackV3;const result=await store.putPack(pack);await refresh();setMessage(`Indexed postflop truth：新增 ${result.imported} nodes，略過 ${result.skipped} immutable versions。`);}catch(error){setMessage(error instanceof Error?error.message:'Solver pack 匯入失敗');}};
 const importTournament=()=>{try{const imported=importTournamentMetadataEnvelope(tournamentJson),byId=new Map(loadTournamentMetadata().map(item=>[item.tournamentId,item]));imported.forEach(item=>byId.set(item.tournamentId,item));const merged=[...byId.values()];saveTournamentMetadata(merged);setTournamentCount(merged.length);setMessage(`Tournament metadata：已保存 ${merged.length} 個 tournaments。`);}catch(error){setMessage(error instanceof Error?error.message:'Tournament metadata 匯入失敗');}};
 return <div data-testid="postflop-truth-lab" className="min-h-screen bg-slate-950 px-4 py-6 text-slate-100 md:px-8"><div className="mx-auto max-w-7xl"><button type="button" onClick={onExit} className="flex items-center gap-2 rounded-xl border border-slate-800 px-4 py-2 text-sm text-slate-300"><ArrowLeft className="h-4 w-4"/>返回</button><section className="mt-6 rounded-3xl border border-cyan-500/20 bg-cyan-500/6 p-6 md:p-8"><div className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">P12 → P13 · indexed postflop truth</div><h1 className="mt-3 text-3xl font-bold">Flop / Turn / River Truth Ops</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-300">v3 exact heads-up semantics 不變；storage 已升級成 IndexedDB context index。舊 localStorage truth 只做一次 migration，不再成為新的寫入來源。</p></section>
 <section className="mt-6 grid gap-4 md:grid-cols-4"><Metric label="Backend" value={diag.backend}/><Metric label="Nodes / Contexts" value={`${diag.nodes} / ${diag.contexts}`}/><Metric label="Packs" value={diag.packs}/><Metric label="Manifest bytes" value={`${(diag.approximateBytes/1024/1024).toFixed(1)} MiB`}/></section>
 <section className="mt-6 grid gap-5 lg:grid-cols-2"><Panel icon={<Database className="h-5 w-5"/>} title="v3 immutable truth pack"><p>匯入 verified v3 JSON。大量 CSV/NDJSON、v4 multiway 與 observability 請用 P13→P17 Production Ops。</p><textarea data-testid="p12-solver-json" value={solverJson} onChange={e=>setSolverJson(e.target.value)} className="mt-3 min-h-56 w-full rounded-xl border border-slate-700 bg-slate-950/60 p-3 font-mono text-xs"/><button data-testid="p12-import-solver" type="button" onClick={importSolver} disabled={!solverJson.trim()} className="mt-3 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-bold text-cyan-950 disabled:opacity-40">匯入 indexed v3 truth pack</button></Panel>
 <Panel icon={<Trophy className="h-5 w-5"/>} title="Tournament metadata registry"><p>保留 explicit JSON path；P15 另支援 full-field lobby CSV automation。</p><textarea data-testid="p12-tournament-json" value={tournamentJson} onChange={e=>setTournamentJson(e.target.value)} className="mt-3 min-h-56 w-full rounded-xl border border-slate-700 bg-slate-950/60 p-3 font-mono text-xs"/><button type="button" onClick={importTournament} disabled={!tournamentJson.trim()} className="mt-3 rounded-xl bg-amber-400 px-4 py-2 text-sm font-bold text-amber-950 disabled:opacity-40">保存 tournament metadata</button><div className="mt-3 text-xs text-slate-500">已保存：{tournamentCount} tournaments</div></Panel></section>
 <section className="mt-5 rounded-2xl border border-emerald-500/15 bg-emerald-500/5 p-5"><div className="flex items-center gap-2 font-semibold text-emerald-200"><ShieldCheck className="h-5 w-5"/>Measured local population</div><p className="mt-2 text-xs leading-6 text-slate-400">仍只保存 raw numerator/denominator，不直接升級 exploit。</p><div className="mt-3 text-sm">已保存 cohort：<b>{cohorts.length}</b></div></section>{message&&<div data-testid="p12-message" className="mt-5 rounded-xl border border-cyan-500/15 bg-cyan-500/6 px-4 py-3 text-sm text-cyan-100">{message}</div>}<button type="button" onClick={()=>{window.location.hash='production-ops';}} className="mt-5 rounded-xl border border-fuchsia-500/30 px-4 py-2 text-sm text-fuchsia-200">開啟 P13→P17 Production Ops</button></div></div>;
}
function Metric({label,value}:{label:string;value:string|number}){return<div className="rounded-2xl border border-slate-800 bg-slate-900/55 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-2 font-mono text-xl font-bold">{value}</div></div>}
function Panel({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return<div className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5"><div className="flex items-center gap-2 font-semibold">{icon}{title}</div><div className="mt-3 text-xs leading-6 text-slate-400">{children}</div></div>}
