import { useEffect, useState } from 'react';
import { ArrowLeft, Database, ShieldCheck } from 'lucide-react';
import { PostflopTruthPackV3, getPostflopTruthStore, migrateLegacyPostflopTruthStorage } from '../../strategy-engine-v3';
import { getMultiwayTruthStore } from '../../strategy-engine-v4';

export function PostflopTruthLab({onExit}:{onExit:()=>void}){
 const v3Store=getPostflopTruthStore(),v4Store=getMultiwayTruthStore();const [solverJson,setSolverJson]=useState(''),[message,setMessage]=useState('');const [v3,setV3]=useState({backend:v3Store.backend,nodes:0,contexts:0,packs:0,approximateBytes:0}),[v4,setV4]=useState({backend:v4Store.backend,nodes:0,contexts:0,packs:0,approximateBytes:0});
 const refresh=async()=>{setV3(await v3Store.diagnostics());setV4(await v4Store.diagnostics());};useEffect(()=>{void(async()=>{await migrateLegacyPostflopTruthStorage(v3Store);await refresh();})();},[]);
 const importSolver=async()=>{try{const pack=JSON.parse(solverJson) as PostflopTruthPackV3;const result=await v3Store.putPack(pack);await refresh();setMessage(`Indexed postflop truth：新增 ${result.imported} nodes，略過 ${result.skipped} immutable versions。`);}catch(error){setMessage(error instanceof Error?error.message:'Solver pack 匯入失敗');}};
 return <div data-testid="postflop-truth-lab" className="min-h-screen bg-slate-950 px-4 py-6 text-slate-100 md:px-8"><div className="mx-auto max-w-7xl"><button type="button" onClick={onExit} className="flex items-center gap-2 rounded-xl border border-slate-800 px-4 py-2 text-sm text-slate-300"><ArrowLeft className="h-4 w-4"/>返回</button><section className="mt-6 rounded-3xl border border-cyan-500/20 bg-cyan-500/6 p-6 md:p-8"><div className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Solver truth storage</div><h1 className="mt-3 text-3xl font-bold">Flop / Turn / River Truth Ops</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-300">這裡只管理訓練用 immutable solver truth。v3 保留 heads-up exact semantics；v4 保留 multiway exact semantics。外部牌局、HH、population observation 與 tournament reconstruction 已移除。</p></section>
 <section className="mt-6 grid gap-4 md:grid-cols-4"><Metric label="v3 nodes / contexts" value={`${v3.nodes} / ${v3.contexts}`}/><Metric label="v3 packs" value={v3.packs}/><Metric label="v4 nodes / contexts" value={`${v4.nodes} / ${v4.contexts}`}/><Metric label="Truth bytes" value={`${((v3.approximateBytes+v4.approximateBytes)/1024/1024).toFixed(1)} MiB`}/></section>
 <section className="mt-6"><Panel icon={<Database className="h-5 w-5"/>} title="v3 immutable truth pack"><p>進階維護用途：匯入 verified v3 JSON。Infinite Hand Generator 不會因缺資料而使用 approximate fallback，也不會從附近 node 猜最佳解。</p><textarea data-testid="p12-solver-json" value={solverJson} onChange={e=>setSolverJson(e.target.value)} className="mt-3 min-h-56 w-full rounded-xl border border-slate-700 bg-slate-950/60 p-3 font-mono text-xs"/><button data-testid="p12-import-solver" type="button" onClick={importSolver} disabled={!solverJson.trim()} className="mt-3 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-bold text-cyan-950 disabled:opacity-40">匯入 indexed v3 truth pack</button></Panel></section>
 <section className="mt-5 rounded-2xl border border-emerald-500/15 bg-emerald-500/5 p-5"><div className="flex items-center gap-2 font-semibold text-emerald-200"><ShieldCheck className="h-5 w-5"/>Training-only truth boundary</div><p className="mt-2 text-xs leading-6 text-slate-400">此頁只維護 solver truth storage。玩家正常流程不需要操作；Infinite Hand Generator 仍以 verified label / validated teaching truth / strategy-equivalent truth 為唯一可評分來源。</p></section>{message&&<div data-testid="p12-message" className="mt-5 rounded-xl border border-cyan-500/15 bg-cyan-500/6 px-4 py-3 text-sm text-cyan-100">{message}</div>}</div></div>;
}
function Metric({label,value}:{label:string;value:string|number}){return<div className="rounded-2xl border border-slate-800 bg-slate-900/55 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-2 font-mono text-xl font-bold">{value}</div></div>}
function Panel({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return<div className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5"><div className="flex items-center gap-2 font-semibold">{icon}{title}</div><div className="mt-3 text-xs leading-6 text-slate-400">{children}</div></div>}
