import { ChangeEvent, ReactNode, useEffect, useState } from 'react';
import { ArrowLeft, BrainCircuit, DatabaseBackup, FileSearch, Gauge, ShieldCheck, Trophy, Waypoints } from 'lucide-react';
import { CausalPrescriptionEvidence } from '../../learning-engine/causalPrescription';
import { discoverExploitCandidate, ExploitCandidateProposal, ExploitSearchConstraints, PopulationResponseModel, validateDiscoveredExploitCandidate } from '../../learning-engine/candidateDiscovery';
import { ExploitHoldoutEvidence } from '../../learning-engine/exploitValidation';
import { buildLongitudinalPokerReport } from '../../learning-engine/longitudinal';
import { annotatePrescriptionsWithPersonalInterventionModel, buildPersonalInterventionModel } from '../../learning-engine/personalInterventionModel';
import { evaluatePopulationDeviation, PopulationDeviationInput } from '../../learning-engine/populationInference';
import { appendReliabilityEvent, buildReliabilityReport, loadReliabilityEvents } from '../../observability/reliability';
import { parseMultiSiteHandHistoryText } from '../../real-game/multiSiteHandHistory';
import { resolveTournamentFgsProbabilityEvidence, resolveTournamentRangeEvidence, staticTournamentEvidenceProvider, StaticTournamentEvidenceProviderEnvelope, TournamentFgsRequest, TournamentRangeRequest } from '../../real-game/tournamentEvidenceProviders';
import { planTruthAcquisition, TruthAcquisitionSource } from '../../solver-data/acquisition';
import { exportFullWorkspaceLines, extractTruthWorkspaceLines, restorePortableLocalState, streamFullWorkspaceToWritable, validateFullWorkspaceLines } from '../../solver-data/fullWorkspace';
import { blobLines, importTruthWorkspaceLines } from '../../solver-data/truthWorkspace';
import { STRATEGY_PROFILES_V2, StrategyProfile, TruthCoverageTargetEnvelope, buildUnifiedTruthCoverage, mergeImmutableProfiles } from '../../strategy-engine-v2';
import { getPostflopTruthStore } from '../../strategy-engine-v3';
import { getMultiwayTruthStore } from '../../strategy-engine-v4';
import { loadHistory } from '../../utils/history';

const CUSTOM_PROFILES_KEY='poker_strategy_profiles_v2',PROVIDERS_KEY='poker_tournament_evidence_providers_v1',CAUSAL_EVIDENCE_KEY='poker_causal_prescription_evidence_v1';
function customProfiles():StrategyProfile[]{try{const parsed=JSON.parse(localStorage.getItem(CUSTOM_PROFILES_KEY)||'[]');return Array.isArray(parsed)?parsed:[];}catch{return[];}}
function allProfiles(){return mergeImmutableProfiles(STRATEGY_PROFILES_V2,customProfiles());}
function loadProviderEnvelopes():StaticTournamentEvidenceProviderEnvelope[]{try{const parsed=JSON.parse(localStorage.getItem(PROVIDERS_KEY)||'[]');return Array.isArray(parsed)?parsed:[];}catch{return[];}}
function saveProviderEnvelope(envelope:StaticTournamentEvidenceProviderEnvelope){const existing=loadProviderEnvelopes(),key=`${envelope.descriptor.id}@${envelope.descriptor.version}`,kept=existing.filter(row=>`${row.descriptor?.id}@${row.descriptor?.version}`!==key);localStorage.setItem(PROVIDERS_KEY,JSON.stringify([...kept,envelope]));}
function savePromotedProfile(profile:StrategyProfile){localStorage.setItem(CUSTOM_PROFILES_KEY,JSON.stringify(mergeImmutableProfiles(customProfiles(),[profile])));}
function telemetry(outcome:'success'|'error'|'conflict',reasonCode?:string,durationMs?:number){try{appendReliabilityEvent(localStorage,{schemaVersion:1,timestamp:Date.now(),operation:'workspace',outcome,reasonCode,durationMs});}catch{/* local observability never blocks an operation */}}
type SavePickerWindow=Window&{showSaveFilePicker?: (options?:unknown)=>Promise<{createWritable:()=>Promise<WritableStream<Uint8Array>>}>};

export function ProductionIntelligenceDashboard({onExit}:{onExit:()=>void}){
 const v3=getPostflopTruthStore(),v4=getMultiwayTruthStore();
 const [status,setStatus]=useState('');
 const [targetJson,setTargetJson]=useState(''),[sourcesJson,setSourcesJson]=useState('[]'),[acquisitionResult,setAcquisitionResult]=useState('');
 const [hhText,setHhText]=useState(''),[hhResult,setHhResult]=useState('');
 const [providerJson,setProviderJson]=useState(''),[providerRequestJson,setProviderRequestJson]=useState(''),[providerResult,setProviderResult]=useState('');
 const [candidateJson,setCandidateJson]=useState(''),[candidateResult,setCandidateResult]=useState('');
 const [causalJson,setCausalJson]=useState(()=>localStorage.getItem(CAUSAL_EVIDENCE_KEY)||'[]'),[personalResult,setPersonalResult]=useState('');
 const [reliabilityResult,setReliabilityResult]=useState('');
 const refreshReliability=()=>{const report=buildReliabilityReport(loadReliabilityEvents(localStorage));setReliabilityResult(JSON.stringify(report,null,2));};
 useEffect(()=>{refreshReliability();},[]);
 const runAcquisition=async()=>{try{const target=JSON.parse(targetJson) as TruthCoverageTargetEnvelope,sources=JSON.parse(sourcesJson) as TruthAcquisitionSource[],coverage=await buildUnifiedTruthCoverage(allProfiles(),v3,v4,target),plan=planTruthAcquisition(coverage,target,sources);setAcquisitionResult(JSON.stringify(plan,null,2));setStatus(`P24 acquisition plan：${plan.gaps.filter(gap=>gap.status==='satisfied').length}/${plan.gaps.length} targets satisfied；weighted ${(plan.weightedCoverage*100).toFixed(1)}%。`);}catch(error){setStatus(error instanceof Error?error.message:'P24 acquisition planning failed.');}};
 const parseMultiSite=()=>{const started=performance.now();try{const result=parseMultiSiteHandHistoryText(hhText);setHhResult(JSON.stringify({hands:result.hands.length,sites:result.detectedSites,rejectedBlocks:result.rejectedBlocks,preview:result.hands.slice(0,5).map(hand=>({id:hand.id,source:hand.source,format:hand.format,hero:hand.heroName,position:hand.heroPosition,actions:hand.actions.length}))},null,2));setStatus(`P25 parsed ${result.hands.length} hands across ${result.detectedSites.join(' / ')||'unknown'}. Full grading remains on Hand History → Leak.`);try{appendReliabilityEvent(localStorage,{schemaVersion:1,timestamp:Date.now(),operation:'hh-parse',outcome:result.hands.length?'success':'unknown',reasonCode:result.hands.length?undefined:'no-supported-hand',durationMs:performance.now()-started,dimension:result.detectedSites.length===1?result.detectedSites[0]:'mixed'});}catch{}}catch(error){setStatus(error instanceof Error?error.message:'P25 parse failed.');}};
 const importProvider=()=>{try{const envelope=JSON.parse(providerJson) as StaticTournamentEvidenceProviderEnvelope,provider=staticTournamentEvidenceProvider(envelope);saveProviderEnvelope(envelope);setProviderResult(JSON.stringify({provider:`${provider.descriptor.id}@${provider.descriptor.version}`,kind:provider.descriptor.kind,capabilities:provider.descriptor.capabilities,storedProviders:loadProviderEnvelopes().length},null,2));setStatus(`P26 provider ${provider.descriptor.id}@${provider.descriptor.version} validated and stored locally.`);}catch(error){setStatus(error instanceof Error?error.message:'P26 provider import failed.');}};
 const resolveProvider=async()=>{try{const input=JSON.parse(providerRequestJson) as {kind:'range'|'fgs';request:TournamentRangeRequest|TournamentFgsRequest;preferredProviderId?:string},providers=loadProviderEnvelopes().map(staticTournamentEvidenceProvider);const result=input.kind==='range'?await resolveTournamentRangeEvidence(providers,input.request as TournamentRangeRequest,input.preferredProviderId):await resolveTournamentFgsProbabilityEvidence(providers,input.request as TournamentFgsRequest,input.preferredProviderId);setProviderResult(JSON.stringify(result,null,2));setStatus(`P26 provider resolution: ${result.status}.`);}catch(error){setStatus(error instanceof Error?error.message:'P26 provider resolution failed.');}};
 const runCandidate=()=>{try{const input=JSON.parse(candidateJson) as {baselineProfileKey:string;responseModel:PopulationResponseModel;deviation:PopulationDeviationInput;constraints?:ExploitSearchConstraints;holdout?:ExploitHoldoutEvidence},baseline=allProfiles().find(profile=>`${profile.id}@${profile.version}`===input.baselineProfileKey);if(!baseline)throw new Error('P27 baselineProfileKey not found in Strategy Profile v2 registry.');const deviation=evaluatePopulationDeviation(input.deviation),proposal=discoverExploitCandidate(baseline,input.responseModel,deviation,input.constraints);let validation:ReturnType<typeof validateDiscoveredExploitCandidate>|undefined;if(input.holdout){validation=validateDiscoveredExploitCandidate(proposal,input.holdout,deviation);if(validation.promotedProfile)savePromotedProfile(validation.promotedProfile);}setCandidateResult(JSON.stringify({proposal:summarizeProposal(proposal),validation:validation?.result,promotedProfileKey:validation?.promotedProfile?`${validation.promotedProfile.id}@${validation.promotedProfile.version}`:undefined},null,2));setStatus(validation?.promotedProfile?'P27 candidate passed independent holdout and was stored as population-exploit.':'P27 generated a bounded derived candidate; no exploit promotion without independent holdout.');}catch(error){setStatus(error instanceof Error?error.message:'P27 candidate discovery failed.');}};
 const runPersonalization=()=>{try{const evidence=JSON.parse(causalJson) as CausalPrescriptionEvidence[],model=buildPersonalInterventionModel(evidence),prescriptions=annotatePrescriptionsWithPersonalInterventionModel(buildLongitudinalPokerReport(loadHistory()).prescriptions,model);localStorage.setItem(CAUSAL_EVIDENCE_KEY,JSON.stringify(evidence));setPersonalResult(JSON.stringify({model,recommendedPrescriptions:prescriptions.filter(item=>item.learnedIntervention)},null,2));setStatus(`P28 learned ${model.recommendations.length} repeated personal intervention recommendation(s); different primary metrics remain separated.`);}catch(error){setStatus(error instanceof Error?error.message:'P28 personalization failed.');}};
 const exportFull=async()=>{const started=performance.now();try{const picker=(window as SavePickerWindow).showSaveFilePicker;if(picker){const handle=await picker({suggestedName:'poker-coach-full-workspace.ndjson',types:[{description:'Poker Coach workspace',accept:{'application/x-ndjson':['.ndjson']}}]}),writable=await handle.createWritable();await streamFullWorkspaceToWritable(localStorage,v3,v4,writable);telemetry('success',undefined,performance.now()-started);setStatus('P29 full workspace streamed to file. Credential-like localStorage keys are excluded.');return;}const lines:string[]=[];for await(const line of exportFullWorkspaceLines(localStorage,v3,v4))lines.push(line);const url=URL.createObjectURL(new Blob([`${lines.join('\n')}\n`],{type:'application/x-ndjson'})),anchor=document.createElement('a');anchor.href=url;anchor.download='poker-coach-full-workspace.ndjson';anchor.click();URL.revokeObjectURL(url);telemetry('success','blob-fallback',performance.now()-started);setStatus('P29 full workspace exported with Blob fallback; File System Access is preferred for very large truth stores.');}catch(error){telemetry('error','export-failed',performance.now()-started);setStatus(error instanceof Error?error.message:'P29 export failed.');}};
 const importFull=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;const started=performance.now();try{const validation=await validateFullWorkspaceLines(blobLines(file));await importTruthWorkspaceLines(extractTruthWorkspaceLines(blobLines(file)),v3,v4,{validateOnly:true});const truth=await importTruthWorkspaceLines(extractTruthWorkspaceLines(blobLines(file)),v3,v4);const local=await restorePortableLocalState(blobLines(file),localStorage);telemetry(local.conflicts.length?'conflict':'success',local.conflicts.length?'local-state-conflict':undefined,performance.now()-started);setStatus(`P29 workspace ${validation.workspaceId} validated。Truth restored v3=${truth.v3Nodes}, v4=${truth.v4Nodes}；local imported=${local.imported}, conflicts=${local.conflicts.length}${local.conflicts.length?` (${local.conflicts.slice(0,5).join(', ')})`:''}。Conflicts were not overwritten.`);refreshReliability();}catch(error){telemetry('error','import-failed',performance.now()-started);setStatus(error instanceof Error?error.message:'P29 import failed.');}event.currentTarget.value='';};
 return <div data-testid="production-intelligence-dashboard" className="min-h-screen bg-slate-950 px-4 py-6 text-slate-100 md:px-8"><div className="mx-auto max-w-7xl"><button onClick={onExit} className="flex items-center gap-2 rounded-xl border border-slate-800 px-4 py-2 text-sm"><ArrowLeft className="h-4 w-4"/>返回</button>
  <section className="mt-6 rounded-3xl border border-violet-500/20 bg-violet-500/5 p-6"><div className="text-xs font-semibold uppercase tracking-[.2em] text-violet-300">P24 → P30 · production intelligence</div><h1 className="mt-3 text-3xl font-bold">Truth Acquisition、Multi-site HH、Evidence Providers、Exploit Discovery、Personal Causality、Full Workspace、Reliability</h1><p className="mt-3 max-w-5xl text-sm leading-7 text-slate-300">自動化只減少人工步驟，不降低證據門檻：未知授權不安裝、多 provider 不偷選、model-derived exploit 先是 candidate、跨裝置分叉不 last-write-wins、telemetry 不保存 raw HH/手牌/玩家名/secret。</p></section>
  <section className="mt-6 grid gap-5 xl:grid-cols-2">
   <Panel icon={<FileSearch className="h-5 w-5"/>} title="P24 · Solver Truth Acquisition"><p>貼 P19 target envelope + source inventory。輸出 missing / ambiguous / full-EV gap；unknown-license source 只列 inventory，不推薦安裝。</p><textarea data-testid="p24-target" value={targetJson} onChange={event=>setTargetJson(event.target.value)} placeholder="TruthCoverageTargetEnvelope JSON" className="mt-3 min-h-28 w-full rounded-xl bg-slate-950 p-3 font-mono text-xs"/><textarea data-testid="p24-sources" value={sourcesJson} onChange={event=>setSourcesJson(event.target.value)} placeholder="TruthAcquisitionSource[] JSON" className="mt-2 min-h-28 w-full rounded-xl bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p24-plan" onClick={()=>void runAcquisition()} className="mt-2 rounded-lg bg-violet-400 px-3 py-2 text-xs font-bold text-violet-950">Build acquisition plan</button>{acquisitionResult&&<Output value={acquisitionResult}/>}</Panel>
   <Panel icon={<Waypoints className="h-5 w-5"/>} title="P25 · Multi-site HH"><p>PokerStars / GG / Winamax / WPN / Party / iPoker 先正規化，再走同一個 P18 replay/integrity contract。這裡可 smoke parse；完整 grading 在 HH → Leak。</p><textarea data-testid="p25-hh" value={hhText} onChange={event=>setHhText(event.target.value)} placeholder="Paste one or more site hand histories" className="mt-3 min-h-44 w-full rounded-xl bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p25-parse" onClick={parseMultiSite} className="mt-2 rounded-lg bg-emerald-400 px-3 py-2 text-xs font-bold text-emerald-950">Parse multi-site HH</button>{hhResult&&<Output value={hhResult}/>}</Panel>
   <Panel icon={<Trophy className="h-5 w-5"/>} title="P26 · Tournament Evidence Providers"><p>可匯入 static provider package，之後以 exact hand/cards/board 或 FGS edge set resolve。多個 provider 同時命中會 Ambiguous，除非明確指定。</p><textarea data-testid="p26-provider" value={providerJson} onChange={event=>setProviderJson(event.target.value)} placeholder="StaticTournamentEvidenceProviderEnvelope JSON" className="mt-3 min-h-32 w-full rounded-xl bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p26-import" onClick={importProvider} className="mt-2 rounded-lg bg-amber-400 px-3 py-2 text-xs font-bold text-amber-950">Validate + store provider</button><textarea data-testid="p26-request" value={providerRequestJson} onChange={event=>setProviderRequestJson(event.target.value)} placeholder='{"kind":"range","request":{...},"preferredProviderId":"optional"}' className="mt-3 min-h-28 w-full rounded-xl bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p26-resolve" onClick={()=>void resolveProvider()} className="mt-2 rounded-lg border border-amber-400/40 px-3 py-2 text-xs text-amber-200">Resolve evidence</button>{providerResult&&<Output value={providerResult}/>}</Panel>
   <Panel icon={<ShieldCheck className="h-5 w-5"/>} title="P27 · Exploit Candidate Discovery"><p>Verified baseline + P16 validated deviation + explicit response model → bounded derived candidate。只有獨立 paired holdout 過 P21 statistical gate 才 promotion。</p><textarea data-testid="p27-candidate" value={candidateJson} onChange={event=>setCandidateJson(event.target.value)} placeholder='{"baselineProfileKey":"...@1","responseModel":{...},"deviation":{...},"constraints":{},"holdout":{...}}' className="mt-3 min-h-52 w-full rounded-xl bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p27-run" onClick={runCandidate} className="mt-2 rounded-lg bg-cyan-400 px-3 py-2 text-xs font-bold text-cyan-950">Search / validate candidate</button>{candidateResult&&<Output value={candidateResult}/>}</Panel>
   <Panel icon={<BrainCircuit className="h-5 w-5"/>} title="P28 · Personal Intervention Model"><p>累積 P22 randomized evidence。至少兩個不同 experiment、同 family + primary metric 才學 intervention；不改 solver truth 或 P17 leak priority。</p><textarea data-testid="p28-evidence" value={causalJson} onChange={event=>setCausalJson(event.target.value)} placeholder="CausalPrescriptionEvidence[] JSON" className="mt-3 min-h-44 w-full rounded-xl bg-slate-950 p-3 font-mono text-xs"/><button data-testid="p28-build" onClick={runPersonalization} className="mt-2 rounded-lg bg-fuchsia-400 px-3 py-2 text-xs font-bold text-fuchsia-950">Build personal model</button>{personalResult&&<Output value={personalResult}/>}</Panel>
   <Panel icon={<DatabaseBackup className="h-5 w-5"/>} title="P29 · Full Workspace"><p>完整 `poker_*` 可攜狀態 + P23 v3/v4 truth streaming。Credential-like keys 排除；import 先 validate，local state conflict 預設不 overwrite。</p><div className="mt-3 flex flex-wrap gap-2"><button data-testid="p29-export" onClick={()=>void exportFull()} className="rounded-lg bg-blue-400 px-3 py-2 text-xs font-bold text-blue-950">Export full workspace</button><label className="rounded-lg border border-blue-400/40 px-3 py-2 text-xs text-blue-200">Validate + restore<input data-testid="p29-import" type="file" accept=".ndjson,text/plain" onChange={importFull} className="hidden"/></label></div></Panel>
   <Panel icon={<Gauge className="h-5 w-5"/>} title="P30 · Reliability"><p>本機 machine-label telemetry：parse/reconstruct/truth lookup/workspace/sync/quota。Unknown 多就回 P24 補資料，不允許放寬 matcher。</p><button data-testid="p30-refresh" onClick={refreshReliability} className="mt-3 rounded-lg bg-slate-200 px-3 py-2 text-xs font-bold text-slate-950">Refresh reliability report</button>{reliabilityResult&&<Output value={reliabilityResult}/>}</Panel>
  </section>{status&&<div data-testid="production-intelligence-status" className="mt-5 rounded-xl border border-violet-500/20 bg-violet-500/6 px-4 py-3 text-sm text-violet-100">{status}</div>}
 </div></div>;
}
function summarizeProposal(proposal:ExploitCandidateProposal){return{id:`${proposal.id}@${proposal.version}`,baselineProfileKey:proposal.baselineProfileKey,populationDeviationId:proposal.populationDeviationId,responseModelKey:proposal.responseModelKey,changedHands:proposal.changedHands,modeledGainBB:proposal.modeledGainBB,trustTier:proposal.candidateProfile.source.trustTier,claim:proposal.claim};}
function Panel({icon,title,children}:{icon:ReactNode;title:string;children:ReactNode}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5 text-xs leading-6 text-slate-400"><div className="flex items-center gap-2 text-base font-semibold text-slate-100">{icon}{title}</div><div className="mt-3">{children}</div></div>}
function Output({value}:{value:string}){return <pre className="mt-3 max-h-56 overflow-auto rounded-xl bg-slate-950 p-3 text-[11px] leading-5 text-slate-300">{value}</pre>}
