import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BarChart3, Database, Network, ShieldCheck, Trophy } from 'lucide-react';
import { buildLongitudinalPokerReport } from '../../learning-engine/longitudinal';
import { PopulationDeviationInput, evaluatePopulationDeviation } from '../../learning-engine/populationInference';
import { tournamentLobbyCsvToMetadata } from '../../real-game/tournamentAdapters';
import { loadTournamentMetadata, saveTournamentMetadata } from '../../real-game/p12Storage';
import { StrategyProfile } from '../../strategy-engine-v2';
import {
  PostflopTruthPackV3,
  getPostflopTruthStore,
  importPostflopTruthNdjson,
  migrateLegacyPostflopTruthStorage,
  solverCsvToPostflopPack,
  textFileLines,
} from '../../strategy-engine-v3';
import { MultiwayTruthPackV4, getMultiwayTruthStore } from '../../strategy-engine-v4';
import { loadHistory } from '../../utils/history';

function loadCustomProfiles():StrategyProfile[]{try{const parsed=JSON.parse(localStorage.getItem('poker_strategy_profiles_v2')||'[]');return Array.isArray(parsed)?parsed:[];}catch{return[];}}

export function ProductionScaleDashboard({onExit}:{onExit:()=>void}){
 const v3=getPostflopTruthStore(),v4=getMultiwayTruthStore();
 const [status,setStatus]=useState('');const [v3Diag,setV3Diag]=useState<{backend:string;nodes:number;contexts:number;packs:number;approximateBytes:number}>({backend:v3.backend,nodes:0,contexts:0,packs:0,approximateBytes:0});const [v4Diag,setV4Diag]=useState<{backend:string;nodes:number;contexts:number}>({backend:v4.backend,nodes:0,contexts:0});
 const [v3Json,setV3Json]=useState('');const [v3Csv,setV3Csv]=useState('');const [v4Json,setV4Json]=useState('');const [lobbyCsv,setLobbyCsv]=useState('');const [populationJson,setPopulationJson]=useState('');const [populationResult,setPopulationResult]=useState('');
 const [ndMeta,setNdMeta]=useState({packId:'stream-pack',version:'1',sourceReference:'file://solver-export'});const report=useMemo(()=>buildLongitudinalPokerReport(loadHistory()),[status]);
 const refresh=async()=>{setV3Diag(await v3.diagnostics());setV4Diag(await v4.diagnostics());};
 useEffect(()=>{void(async()=>{const migration=await migrateLegacyPostflopTruthStorage(v3);await refresh();if(!migration.alreadyDone&&migration.migrated)setStatus(`Migrated ${migration.migrated} legacy v3 nodes into indexed truth store.`);})();},[]);
 const importV3Json=async()=>{try{const pack=JSON.parse(v3Json) as PostflopTruthPackV3;const r=await v3.putPack(pack);await refresh();setStatus(`v3 JSON: imported ${r.imported}, skipped ${r.skipped}.`);}catch(e){setStatus(e instanceof Error?e.message:'v3 import failed');}};
 const importV3Csv=async()=>{try{const pack=solverCsvToPostflopPack(v3Csv,undefined,{packId:`csv-${Date.now()}`,version:'1'});const r=await v3.putPack(pack);await refresh();setStatus(`v3 mapped CSV: imported ${r.imported}, skipped ${r.skipped}.`);}catch(e){setStatus(e instanceof Error?e.message:'CSV import failed');}};
 const importV4=async()=>{try{const pack=JSON.parse(v4Json) as MultiwayTruthPackV4;const r=await v4.putPack(pack);await refresh();setStatus(`v4 multiway: imported ${r.imported}, skipped ${r.skipped}.`);}catch(e){setStatus(e instanceof Error?e.message:'v4 import failed');}};
 const importLobby=()=>{try{const incoming=tournamentLobbyCsvToMetadata(lobbyCsv),byId=new Map(loadTournamentMetadata().map(item=>[item.tournamentId,item]));incoming.forEach(item=>byId.set(item.tournamentId,item));saveTournamentMetadata([...byId.values()]);setStatus(`P15 tournament registry: ${incoming.length} tournament(s) imported; ${byId.size} total.`);}catch(e){setStatus(e instanceof Error?e.message:'Tournament import failed');}};
 const evaluatePopulation=()=>{try{const envelope=JSON.parse(populationJson) as {input:PopulationDeviationInput;linkedProfileKey?:string};const linked=envelope.linkedProfileKey?loadCustomProfiles().find(p=>`${p.id}@${p.version}`===envelope.linkedProfileKey):undefined;const result=evaluatePopulationDeviation(envelope.input,linked);setPopulationResult(JSON.stringify(result,null,2));setStatus(`P16 population evidence: ${result.status}${result.exploitEligible?' · exploit profile linked':''}.`);}catch(e){setStatus(e instanceof Error?e.message:'Population evaluation failed');}};
 const importNdjson=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const r=await importPostflopTruthNdjson(textFileLines(file),v3,ndMeta);await refresh();setStatus(`NDJSON stream: imported ${r.imported}, skipped ${r.skipped}.`);}catch(e){setStatus(e instanceof Error?e.message:'NDJSON import failed');}event.currentTarget.value='';};
 return <div data-testid="production-scale-dashboard" className="min-h-screen bg-slate-950 px-4 py-6 text-slate-100 md:px-8"><div className="mx-auto max-w-7xl">
  <button type="button" onClick={onExit} className="flex items-center gap-2 rounded-xl border border-slate-800 px-4 py-2 text-sm"><ArrowLeft className="h-4 w-4"/>返回</button>
  <section className="mt-6 rounded-3xl border border-cyan-500/20 bg-cyan-500/6 p-6"><div className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">P13 → P17 · production scale</div><h1 className="mt-3 text-3xl font-bold">Truth scale、Multiway、Tournament、Population、Longitudinal Coach</h1><p className="mt-3 max-w-5xl text-sm leading-7 text-slate-300">所有升級都維持 fail-toward-Unknown：大資料用 index，不用全量 filter；multiway 只吃 v4 truth；牌池偏差要 holdout replication；長期改善預設仍是 observational。</p></section>
  <section className="mt-5 grid gap-3 md:grid-cols-4"><Metric label="v3 backend" value={v3Diag.backend}/><Metric label="v3 nodes / contexts" value={`${v3Diag.nodes} / ${v3Diag.contexts}`}/><Metric label="v3 packs / bytes" value={`${v3Diag.packs} / ${(v3Diag.approximateBytes/1024/1024).toFixed(1)} MiB`}/><Metric label="v4 nodes / contexts" value={`${v4Diag.nodes} / ${v4Diag.contexts}`}/></section>
  <section className="mt-6 grid gap-5 xl:grid-cols-2">
   <Panel icon={<Database className="h-5 w-5"/>} title="P13-A/B · Indexed truth + solver adapters"><p>v3 JSON、normalized/mapped CSV、NDJSON streaming 都進 IndexedDB context index。CSV 只有欄位能明確映射才接受。</p><textarea data-testid="p13-v3-json" value={v3Json} onChange={e=>setV3Json(e.target.value)} className="mt-3 min-h-32 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs" placeholder="Postflop Truth Pack v3 JSON"/><button data-testid="p13-import-v3" onClick={importV3Json} className="mt-2 rounded-lg bg-cyan-500 px-3 py-2 text-xs font-bold text-cyan-950">Import v3 JSON</button><textarea value={v3Csv} onChange={e=>setV3Csv(e.target.value)} className="mt-3 min-h-28 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs" placeholder="Normalized solver CSV"/><button onClick={importV3Csv} className="mt-2 rounded-lg border border-cyan-500/30 px-3 py-2 text-xs">Map CSV → v3</button><div className="mt-3 grid grid-cols-3 gap-2"><input value={ndMeta.packId} onChange={e=>setNdMeta({...ndMeta,packId:e.target.value})} className="rounded-lg bg-slate-950 p-2 text-xs"/><input value={ndMeta.version} onChange={e=>setNdMeta({...ndMeta,version:e.target.value})} className="rounded-lg bg-slate-950 p-2 text-xs"/><input value={ndMeta.sourceReference} onChange={e=>setNdMeta({...ndMeta,sourceReference:e.target.value})} className="rounded-lg bg-slate-950 p-2 text-xs"/></div><label className="mt-2 block text-xs text-cyan-200">Stream .ndjson<input data-testid="p13-ndjson" type="file" accept=".ndjson,.jsonl,text/plain" onChange={importNdjson} className="mt-1 block w-full text-xs"/></label></Panel>
   <Panel icon={<Network className="h-5 w-5"/>} title="P14 · Multiway Truth v4"><p>3-way+ context 必須列出每個 active opponent 的 position + remaining stack。v3 heads-up truth 永不 fallback。</p><textarea data-testid="p14-v4-json" value={v4Json} onChange={e=>setV4Json(e.target.value)} className="mt-3 min-h-48 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs" placeholder="Multiway Truth Pack v4 JSON"/><button data-testid="p14-import-v4" onClick={importV4} className="mt-2 rounded-lg bg-violet-400 px-3 py-2 text-xs font-bold text-violet-950">Import v4 multiway truth</button></Panel>
   <Panel icon={<Trophy className="h-5 w-5"/>} title="P15 · Tournament automation"><p>Full-field lobby/snapshot CSV 直接建立 tournament registry；table HH 永遠不會被當 full field。</p><textarea data-testid="p15-lobby-csv" value={lobbyCsv} onChange={e=>setLobbyCsv(e.target.value)} className="mt-3 min-h-44 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs" placeholder="normalized tournament lobby CSV"/><button data-testid="p15-import-lobby" onClick={importLobby} className="mt-2 rounded-lg bg-amber-400 px-3 py-2 text-xs font-bold text-amber-950">Import full-field snapshots</button></Panel>
   <Panel icon={<ShieldCheck className="h-5 w-5"/>} title="P16 · Replicated population evidence"><p>輸入 predeclared metric + solver baseline + training/holdout raw counts。兩個 split 都過 sample、practical delta、95% interval 才是 validated deviation；沒有 linked population-exploit profile 不產生 exploit。</p><textarea data-testid="p16-json" value={populationJson} onChange={e=>setPopulationJson(e.target.value)} className="mt-3 min-h-44 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-xs" placeholder='{"input":{...},"linkedProfileKey":"population:...@..."}'/><button data-testid="p16-evaluate" onClick={evaluatePopulation} className="mt-2 rounded-lg bg-emerald-400 px-3 py-2 text-xs font-bold text-emerald-950">Validate deviation</button>{populationResult&&<pre className="mt-3 max-h-48 overflow-auto rounded-xl bg-slate-950 p-3 text-[11px]">{populationResult}</pre>}</Panel>
  </section>
  <section className="mt-6 rounded-2xl border border-fuchsia-500/20 bg-fuchsia-500/5 p-5"><div className="flex items-center gap-2 font-semibold text-fuchsia-200"><BarChart3 className="h-5 w-5"/>P17 · Longitudinal Coach</div><div className="mt-4 grid gap-3 md:grid-cols-3"><Metric label="Months with verified outcomes" value={report.months.length}/><Metric label="Families tracked" value={report.families.length}/><Metric label="Current prescriptions" value={report.prescriptions.length}/></div><div className="mt-4 space-y-2">{report.prescriptions.slice(0,8).map((item,index)=><div key={item.decisionFamilyId} className="rounded-xl border border-slate-800 bg-slate-950/40 p-3 text-xs"><b>#{index+1} {item.decisionFamilyId}</b> · priority {item.priority.toFixed(3)}<div className="mt-1 text-slate-400">{item.reason}</div></div>)}{!report.prescriptions.length&&<div className="text-sm text-slate-500">尚無足夠 verified real-game regret 可產生 prescription。</div>}</div><p className="mt-4 text-[11px] leading-5 text-slate-500">{report.caveats.join(' ')}</p></section>
  {status&&<div data-testid="production-scale-status" className="mt-5 rounded-xl border border-cyan-500/20 bg-cyan-500/6 px-4 py-3 text-sm text-cyan-100">{status}</div>}
 </div></div>;
}
function Metric({label,value}:{label:string;value:string|number}){return<div className="rounded-xl border border-slate-800 bg-slate-900/55 p-3"><div className="text-[11px] text-slate-500">{label}</div><div className="mt-1 break-words font-mono font-bold">{value}</div></div>}
function Panel({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return<div className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5 text-xs leading-6 text-slate-400"><div className="flex items-center gap-2 text-base font-semibold text-slate-100">{icon}{title}</div><div className="mt-3">{children}</div></div>}
