import assert from 'node:assert/strict';
import test from 'node:test';
import { MultiwayTruthNodeV4, createMultiwayTruthStore, findExactVerifiedMultiwayNode, verifiedMultiwayRegret } from '../src/strategy-engine-v4';
import { parseHandHistoryText } from '../src/real-game/handHistory';
import { extractObservedMultiwayDecisions } from '../src/real-game/multiwayState';
import { buildVerifiedMultiwayLeakEvidence } from '../src/real-game/multiwayLeakPipeline';

function fixture():MultiwayTruthNodeV4{return{schemaVersion:4,id:'mw:btn-sb-bb-a84',version:'1',name:'BTN vs SB vs BB A84r',description:'fixture',context:{format:'cash',tableSize:'6max',street:'Flop',heroPosition:'btn',heroRemainingStackBB:97.5,opponents:[{position:'sb',remainingStackBB:97.5},{position:'bb',remainingStackBB:97.5}],playersInHand:3,potBB:7.5,spr:13,toCallBB:0,board:['Ah','8c','4d'],preflopLine:[{actor:'utg',action:'fold'},{actor:'hj',action:'fold'},{actor:'co',action:'fold'},{actor:'btn',action:'raise',toBB:2.5},{actor:'sb',action:'call'},{actor:'bb',action:'call'}],streetLine:[{actor:'sb',action:'check'},{actor:'bb',action:'check'}],lastAggressorPosition:'btn',rakePercent:5,rakeCapBB:2},source:{type:'solver',trustTier:'verified-solver',label:'fixture',reference:'fixture://multiway',solverName:'FixtureMultiway',solverVersion:'1',generatedAt:'2026-08-21T00:00:00Z'},strategyByCombo:{AsKd:{check:0.25,bet:0.75}},evByCombo:{AsKd:{check:1,bet:1.3}},tags:['test']};}

const hh=`PokerStars Hand #14001: Hold'em No Limit ($0.50/$1.00 USD) - 2026/08/21 02:00:00 ET\nTable 'MW' 6-max Seat #1 is the button\nSeat 1: Hero ($100 in chips)\nSeat 2: SB ($100 in chips)\nSeat 3: BB ($100 in chips)\nSeat 4: UTG ($100 in chips)\nSeat 5: HJ ($100 in chips)\nSeat 6: CO ($100 in chips)\nSB: posts small blind $0.50\nBB: posts big blind $1\n*** HOLE CARDS ***\nDealt to Hero [As Kd]\nUTG: folds\nHJ: folds\nCO: folds\nHero: raises $1.50 to $2.50\nSB: calls $2\nBB: calls $1.50\n*** FLOP *** [Ah 8c 4d]\nSB: checks\nBB: checks\nHero: checks\n*** TURN *** [Ah 8c 4d] [7s]`;

test('P14 HH replay preserves every active opponent and exact multiway geometry',()=>{const hand=parseHandHistoryText(hh)[0];const decision=extractObservedMultiwayDecisions(hand,{rakePercent:5,rakeCapBB:2})[0];assert.ok(decision);assert.equal(decision.query.playersInHand,3);assert.equal(decision.query.potBB,7.5);assert.equal(decision.query.spr,13);assert.deepEqual(decision.query.opponents,[{position:'sb',remainingStackBB:97.5},{position:'bb',remainingStackBB:97.5}]);assert.equal(findExactVerifiedMultiwayNode([fixture()],decision.query)?.id,fixture().id);});

test('P14 exact multiway truth refuses a missing opponent and requires sourced EV',()=>{const hand=parseHandHistoryText(hh)[0];const q=extractObservedMultiwayDecisions(hand,{rakePercent:5,rakeCapBB:2})[0].query;assert.equal(findExactVerifiedMultiwayNode([fixture()],{...q,opponents:q.opponents?.slice(0,1),playersInHand:2}),undefined);const regret=verifiedMultiwayRegret(fixture(),['As','Kd'],'check');assert.ok(regret);assert.ok(Math.abs(regret!.evLossBB-0.3)<1e-9);});

test('P14 multiway HH writes verified regret only through unique v4 truth',async()=>{const store=createMultiwayTruthStore(true);await store.putPack({schemaVersion:4,packId:'mw-pack',version:'1',exportedAt:'2026-08-21T00:00:00Z',sourceReference:'fixture://multiway',nodes:[fixture()]});const result=await buildVerifiedMultiwayLeakEvidence(parseHandHistoryText(hh),store,{rakePercent:5,rakeCapBB:2});assert.equal(result.gradedDecisions,1);assert.equal(result.history[0].judgment,'verified-multiway-regret');assert.equal(result.history[0].truthSourceId,fixture().id);});
