import assert from 'node:assert/strict';
import test from 'node:test';
import { buildUnifiedTruthCoverage } from '../src/strategy-engine-v2';
import { PostflopTruthNode, createPostflopTruthStore, postflopContextKey } from '../src/strategy-engine-v3';
import { createMultiwayTruthStore } from '../src/strategy-engine-v4';

function node(version:string):PostflopTruthNode{return{schemaVersion:3,id:'p19:a84',version,name:'A84',description:'fixture',context:{format:'cash',tableSize:'6max',street:'Flop',heroPosition:'btn',villainPosition:'bb',playersInHand:2,effectiveStackBB:97.5,potBB:5.5,spr:17.727,toCallBB:0,board:['Ah','8c','4d'],preflopLine:[{actor:'btn',action:'raise',toBB:2.5},{actor:'bb',action:'call'}],streetLine:[{actor:'bb',action:'check'}],lastAggressorPosition:'btn',rakePercent:5,rakeCapBB:2},source:{type:'solver',trustTier:'verified-solver',label:'fixture',reference:`fixture://p19/${version}`,solverName:'Fixture',solverVersion:version,generatedAt:'2026-08-21T00:00:00Z',disclaimer:'Synthetic test fixture.'},strategyByCombo:{AsKd:{check:0.3,bet:0.7},QsQh:{check:1}},evByCombo:{AsKd:{check:1,bet:1.2}},tags:['test']};}

test('P19 portfolio counts only uniquely usable full-EV combos and exposes ambiguity',async()=>{const v3=createPostflopTruthStore(true),v4=createMultiwayTruthStore(true);await v3.putPack({schemaVersion:3,packId:'p19',version:'1',exportedAt:'2026-08-21T00:00:00Z',sourceReference:'fixture://p19',nodes:[node('1')]});let report=await buildUnifiedTruthCoverage([],v3,v4,{schemaVersion:1,id:'targets',version:'1',generatedAt:'2026-08-21T00:00:00Z',reference:'fixture://targets',targets:[{id:'a84',engine:'v3-heads-up',label:'A84 target',contextKey:postflopContextKey(node('1').context),weight:1,minimumUniqueCombos:2,minimumFullEvCombos:1}]});assert.equal(report.byEngine['v3-heads-up'].uniqueCombos,2);assert.equal(report.byEngine['v3-heads-up'].fullEvCombos,1);assert.equal(report.weightedTargetCoverage,1);await v3.putPack({schemaVersion:3,packId:'p19-v2',version:'2',exportedAt:'2026-08-21T00:00:00Z',sourceReference:'fixture://p19/2',nodes:[node('2')]});report=await buildUnifiedTruthCoverage([],v3,v4);assert.equal(report.byEngine['v3-heads-up'].uniqueCombos,0);assert.equal(report.byEngine['v3-heads-up'].ambiguousCombos,2);});
