import assert from 'node:assert/strict';
import test from 'node:test';
import { applyFgsProbabilityEvidence, attachExactTournamentRangeEquity, evaluateTournamentRangeEvidence, TournamentRangeEvidence } from '../src/real-game/tournamentDecisionEvidence';
import { TournamentHandContext } from '../src/real-game/tournamentContext';

const rangeEvidence: TournamentRangeEvidence={schemaVersion:1,id:'range:2001',version:'1',handId:'2001',heroCards:['As','Kd'],board:['Ah','8c','4d','7s','2c'],villainRange:[{hand:'QQ'}],reference:'fixture://range',generatedAt:'2026-08-21T00:00:00Z',methodology:'Explicit reviewed shove range.'};
const draft={schemaVersion:1,id:'icm:2001',version:'1',handId:'2001',model:'icm',heroId:'Hero',players:[{id:'Hero',stack:100},{id:'Villain',stack:80},{id:'Other',stack:50}],payouts:[100,60,40],utilityUnit:'dollar-ev',chosenAction:'call',reference:'fixture://mtt',generatedAt:'2026-08-21T00:00:00Z',methodology:'Full-field snapshot.',villainId:'Villain',amountAtRisk:80} satisfies Omit<TournamentHandContext,'showdownEquity'>;

test('P20 exact range enumeration can attach reproducible showdown equity to ICM/PKO context',()=>{const evaluation=evaluateTournamentRangeEvidence(rangeEvidence);assert.equal(evaluation.status,'exact-eligible');assert.equal(evaluation.method,'exact');const attached=attachExactTournamentRangeEquity(draft,rangeEvidence);assert.equal(attached.status,'attached');assert.ok(attached.context);assert.equal(attached.context!.showdownEquity,evaluation.equityFraction);assert.match(attached.context!.reference,/fixture:\/\/range/);});

test('P20 Monte Carlo range evidence stays simulation-only and cannot upgrade exact-math tournament context',()=>{const simulated={...rangeEvidence,id:'range:preflop',board:[],exactStateLimit:1,iterations:1000,seed:42};const evaluation=evaluateTournamentRangeEvidence(simulated);assert.equal(evaluation.status,'simulation-only');assert.equal(evaluation.method,'monte-carlo');const attached=attachExactTournamentRangeEquity(draft,simulated);assert.equal(attached.status,'simulation-only');assert.equal(attached.context,undefined);});

test('P20 FGS probability evidence must cover exactly the supplied tree edges and sum to one',()=>{const state=[{id:'Hero',stack:100},{id:'Villain',stack:100}];const trees=[{action:'fold',root:{id:'fold-root',players:state,children:[{id:'fold-a'},{id:'fold-b'}]}},{action:'call',root:{id:'call-root',players:state,children:[{id:'call-a'},{id:'call-b'}]}}];const evidence={schemaVersion:1 as const,id:'fgs-probs',version:'1',handId:'2001',reference:'fixture://fgs-model',generatedAt:'2026-08-21T00:00:00Z',methodology:'Explicit external branch model.',edges:[{parentId:'fold-root',childId:'fold-a',probability:.5},{parentId:'fold-root',childId:'fold-b',probability:.5},{parentId:'call-root',childId:'call-a',probability:.4},{parentId:'call-root',childId:'call-b',probability:.6}]};const applied=applyFgsProbabilityEvidence(trees,evidence);assert.equal(applied.actionTrees[1].root.children?.[0].probability,.4);assert.throws(()=>applyFgsProbabilityEvidence(trees,{...evidence,edges:evidence.edges.slice(0,3)}),/missing/);});
