import assert from 'node:assert/strict';
import test from 'node:test';
import { annotatePrescriptionsWithRandomizedEvidence, buildCausalPrescriptionEvidence } from '../src/learning-engine/causalPrescription';
import { createRandomizedBlockExperiment, evaluateLearningExperiment } from '../src/learning-engine/experiment';
import { HistoryItem } from '../src/types';

const start=10_000;const spec=createRandomizedBlockExperiment({id:'exp-22',version:'1',preRegisteredAt:9_000,startAt:start,blockDurationMs:1_000,blockCount:4,arms:[{id:'a',label:'Contrastive',intervention:'contrastive-pairs'},{id:'b',label:'Recall',intervention:'delayed-recall'}],metric:'holdout-accuracy',assignmentSeed:'p22',hypothesis:'Contrastive training improves holdout accuracy.',minSamplesPerArm:2});
const history:HistoryItem[]=spec.blocks.flatMap(block=>Array.from({length:2},(_,index)=>({schemaVersion:6,scenarioId:`${block.id}:${index}`,category:['test'],score:block.armId==='a'?10:0,judgment:'test',timestamp:block.startAt+100+index,trainingType:'solver-benchmark',solverCorpusRole:'holdout',correct:block.armId==='a'})));

test('P22 sufficient preregistered N-of-1 evidence recommends intervention only for its preregistered leak family',()=>{const result=evaluateLearningExperiment(history,spec);assert.equal(result.status,'randomized-n-of-1');const evidence=buildCausalPrescriptionEvidence(spec,result,{schemaVersion:1,id:'target-22',version:'1',experimentId:spec.id,experimentVersion:spec.version,targetDecisionFamilyId:'river.bluff-catch',registeredAt:8_500,reference:'fixture://target',hypothesis:spec.hypothesis});assert.ok(evidence);const annotated=annotatePrescriptionsWithRandomizedEvidence([{decisionFamilyId:'river.bluff-catch',verifiedObservations:10,averageEvLossBB:.2,recentTrainingAttempts:4,priority:1,reason:'fixture'},{decisionFamilyId:'bb.defense',verifiedObservations:10,averageEvLossBB:.1,recentTrainingAttempts:4,priority:.5,reason:'fixture'}],[evidence!]);assert.equal(annotated[0].randomizedEvidence?.recommendedIntervention,'contrastive-pairs');assert.equal(annotated[1].randomizedEvidence,undefined);assert.equal(annotated[0].priority,1);});

test('P22 retrospective target assignment is rejected and insufficient experiment cannot drive coach intervention',()=>{assert.throws(()=>buildCausalPrescriptionEvidence(spec,evaluateLearningExperiment([],spec),{schemaVersion:1,id:'late',version:'1',experimentId:spec.id,experimentVersion:spec.version,targetDecisionFamilyId:'river.bluff-catch',registeredAt:9_500,reference:'fixture://late',hypothesis:spec.hypothesis}),/registered/);const insufficient=evaluateLearningExperiment([],spec);const evidence=buildCausalPrescriptionEvidence(spec,insufficient,{schemaVersion:1,id:'target',version:'1',experimentId:spec.id,experimentVersion:spec.version,targetDecisionFamilyId:'river.bluff-catch',registeredAt:8_500,reference:'fixture://target',hypothesis:spec.hypothesis});assert.equal(evidence,undefined);});
