import assert from 'node:assert/strict';
import test from 'node:test';
import { exportTruthWorkspaceLines, importTruthWorkspaceLines } from '../src/solver-data/truthWorkspace';
import { PostflopTruthNode, createPostflopTruthStore } from '../src/strategy-engine-v3';
import { MultiwayTruthNodeV4, createMultiwayTruthStore } from '../src/strategy-engine-v4';

const source={type:'solver' as const,trustTier:'verified-solver' as const,label:'fixture',reference:'fixture://workspace',solverName:'Fixture',solverVersion:'1',generatedAt:'2026-08-21T00:00:00Z',disclaimer:'Synthetic workspace fixture.'};
function v3node():PostflopTruthNode{return{schemaVersion:3,id:'ws-v3',version:'1',name:'v3',description:'fixture',context:{format:'cash',tableSize:'6max',street:'River',heroPosition:'btn',villainPosition:'bb',playersInHand:2,effectiveStackBB:80,potBB:40,spr:2,toCallBB:0,board:['Ah','8c','4d','7s','2c'],preflopLine:[{actor:'btn',action:'raise',toBB:2.5},{actor:'bb',action:'call'}],streetLine:[{actor:'bb',action:'check'}],lastAggressorPosition:'btn',rakePercent:5,rakeCapBB:2},source,strategyByCombo:{AsKd:{check:.5,bet:.5}},evByCombo:{AsKd:{check:1,bet:1.1}},tags:['test']};}
function v4node():MultiwayTruthNodeV4{return{schemaVersion:4,id:'ws-v4',version:'1',name:'v4',description:'fixture',context:{format:'cash',tableSize:'6max',street:'Flop',heroPosition:'btn',heroRemainingStackBB:90,opponents:[{position:'sb',remainingStackBB:90},{position:'bb',remainingStackBB:90}],playersInHand:3,potBB:10,spr:9,toCallBB:0,board:['Ah','8c','4d'],preflopLine:[{actor:'btn',action:'raise',toBB:3},{actor:'sb',action:'call'},{actor:'bb',action:'call'}],streetLine:[{actor:'sb',action:'check'},{actor:'bb',action:'check'}],lastAggressorPosition:'btn',rakePercent:5,rakeCapBB:2},source,strategyByCombo:{AsKd:{check:.3,bet:.7}},evByCombo:{AsKd:{check:1,bet:1.2}},tags:['test']};}
async function* asLines(lines:string[]){for(const line of lines)yield line;}

test('P23 exports, validates, and restores v3/v4 truth without materializing a combined node array',async()=>{const sourceV3=createPostflopTruthStore(true),sourceV4=createMultiwayTruthStore(true);await sourceV3.putPack({schemaVersion:3,packId:'ws3',version:'1',exportedAt:'2026-08-21T00:00:00Z',sourceReference:'fixture://workspace',nodes:[v3node()]});await sourceV4.putPack({schemaVersion:4,packId:'ws4',version:'1',exportedAt:'2026-08-21T00:00:00Z',sourceReference:'fixture://workspace',nodes:[v4node()]});const lines:string[]=[];for await(const line of exportTruthWorkspaceLines(sourceV3,sourceV4,'workspace-test'))lines.push(line);assert.ok(lines.length>=5);const targetV3=createPostflopTruthStore(true),targetV4=createMultiwayTruthStore(true);const validated=await importTruthWorkspaceLines(asLines(lines),targetV3,targetV4,{validateOnly:true});assert.equal(validated.validated,true);assert.equal((await targetV3.diagnostics()).nodes,0);const restored=await importTruthWorkspaceLines(asLines(lines),targetV3,targetV4);assert.equal(restored.imported,true);assert.equal((await targetV3.diagnostics()).nodes,1);assert.equal((await targetV4.diagnostics()).nodes,1);assert.equal((await targetV3.listManifests()).length,1);assert.equal((await targetV4.listManifests()).length,1);});

test('P23 rejects truncated or count-mismatched workspace before calling it valid',async()=>{const v3=createPostflopTruthStore(true),v4=createMultiwayTruthStore(true);const bad=[JSON.stringify({kind:'workspace-header',schemaVersion:1,workspaceId:'bad',generatedAt:'2026-08-21T00:00:00Z'}),JSON.stringify({kind:'workspace-footer',v3Nodes:1,v4Nodes:0,v3Manifests:0,v4Manifests:0})];await assert.rejects(()=>importTruthWorkspaceLines(asLines(bad),v3,v4,{validateOnly:true}),/counts/);});
