export type ReliabilityOperation='hh-parse'|'hh-reconstruct'|'truth-lookup'|'indexeddb'|'workspace'|'sync'|'experiment'|'storage-quota';
export type ReliabilityOutcome='success'|'unsupported'|'unknown'|'error'|'conflict';
export interface ReliabilityEvent {schemaVersion:1;timestamp:number;operation:ReliabilityOperation;outcome:ReliabilityOutcome;reasonCode?:string;durationMs?:number;dimension?:string;value?:number;}
export interface ReliabilityOperationReport {operation:ReliabilityOperation;attempts:number;success:number;unsupported:number;unknown:number;errors:number;conflicts:number;successRate:number;p50DurationMs?:number;p95DurationMs?:number;}
export interface ReliabilityReport {windowDays:number;events:number;byOperation:ReliabilityOperationReport[];topReasons:Array<{reasonCode:string;count:number}>;recommendations:string[];latestStorageQuotaRatio?:number;caveats:string[];}
export interface ReliabilityStorage {getItem(key:string):string|null;setItem(key:string,value:string):void;}
export const RELIABILITY_STORAGE_KEY='poker_reliability_events_v1';
const OPERATIONS:ReliabilityOperation[]=['hh-parse','hh-reconstruct','truth-lookup','indexeddb','workspace','sync','experiment','storage-quota'];const OUTCOMES:ReliabilityOutcome[]=['success','unsupported','unknown','error','conflict'];
function percentile(values:number[],p:number){if(!values.length)return undefined;const sorted=[...values].sort((a,b)=>a-b),index=Math.min(sorted.length-1,Math.max(0,Math.ceil(p*sorted.length)-1));return sorted[index];}

/** Event schema deliberately rejects free-text payloads; reason/dimension are short machine labels only. */
export function sanitizeReliabilityEvent(raw:ReliabilityEvent):ReliabilityEvent{
 if(!raw||raw.schemaVersion!==1||!Number.isFinite(raw.timestamp)||!OPERATIONS.includes(raw.operation)||!OUTCOMES.includes(raw.outcome))throw new Error('Invalid reliability event.');
 if(raw.reasonCode!==undefined&&!/^[a-z0-9][a-z0-9._-]{0,63}$/i.test(raw.reasonCode))throw new Error('Reliability reasonCode must be a short machine label, not raw hand/user content.');
 if(raw.dimension!==undefined&&!/^[a-z0-9][a-z0-9._:-]{0,63}$/i.test(raw.dimension))throw new Error('Reliability dimension must be a short machine label.');
 if(raw.durationMs!==undefined&&(!Number.isFinite(raw.durationMs)||raw.durationMs<0))throw new Error('Reliability durationMs must be non-negative.');if(raw.value!==undefined&&!Number.isFinite(raw.value))throw new Error('Reliability value must be finite.');
 return{schemaVersion:1,timestamp:raw.timestamp,operation:raw.operation,outcome:raw.outcome,reasonCode:raw.reasonCode,durationMs:raw.durationMs,dimension:raw.dimension,value:raw.value};
}
export function loadReliabilityEvents(storage:ReliabilityStorage):ReliabilityEvent[]{try{const raw=JSON.parse(storage.getItem(RELIABILITY_STORAGE_KEY)||'[]') as ReliabilityEvent[];return Array.isArray(raw)?raw.map(sanitizeReliabilityEvent):[];}catch{return[];}}
export function appendReliabilityEvent(storage:ReliabilityStorage,event:ReliabilityEvent,maxEvents=5000):ReliabilityEvent[]{if(!Number.isInteger(maxEvents)||maxEvents<100)throw new Error('maxEvents must be >=100.');const next=[...loadReliabilityEvents(storage),sanitizeReliabilityEvent(event)].sort((a,b)=>a.timestamp-b.timestamp).slice(-maxEvents);storage.setItem(RELIABILITY_STORAGE_KEY,JSON.stringify(next));return next;}

export function buildReliabilityReport(events:ReliabilityEvent[],now=Date.now(),windowDays=30):ReliabilityReport{
 if(!Number.isFinite(windowDays)||windowDays<=0)throw new Error('windowDays must be positive.');const floor=now-windowDays*86400000,rows=events.map(sanitizeReliabilityEvent).filter(event=>event.timestamp>=floor&&event.timestamp<=now);const byOperation:ReliabilityOperationReport[]=OPERATIONS.map(operation=>{const subset=rows.filter(event=>event.operation===operation),durations=subset.map(event=>event.durationMs).filter((value):value is number=>typeof value==='number');const success=subset.filter(event=>event.outcome==='success').length,unsupported=subset.filter(event=>event.outcome==='unsupported').length,unknown=subset.filter(event=>event.outcome==='unknown').length,errors=subset.filter(event=>event.outcome==='error').length,conflicts=subset.filter(event=>event.outcome==='conflict').length;return{operation,attempts:subset.length,success,unsupported,unknown,errors,conflicts,successRate:subset.length?success/subset.length:0,p50DurationMs:percentile(durations,.5),p95DurationMs:percentile(durations,.95)};}).filter(row=>row.attempts>0);
 const reasonCounts=new Map<string,number>();rows.forEach(event=>{if(event.reasonCode)reasonCounts.set(event.reasonCode,(reasonCounts.get(event.reasonCode)||0)+1);});const topReasons=[...reasonCounts.entries()].map(([reasonCode,count])=>({reasonCode,count})).sort((a,b)=>b.count-a.count||a.reasonCode.localeCompare(b.reasonCode)).slice(0,10),recommendations:string[]=[];
 const parse=byOperation.find(row=>row.operation==='hh-parse');if(parse&&parse.successRate<.98)recommendations.push(`HH parse success is ${(parse.successRate*100).toFixed(1)}%; prioritize the highest-frequency parser reason codes before adding new poker features.`);const reconstruct=byOperation.find(row=>row.operation==='hh-reconstruct');if(reconstruct&&(reconstruct.unsupported+reconstruct.errors)/reconstruct.attempts>.02)recommendations.push('HH reconstruction has >2% unsupported/error outcomes; inspect geometry/site cohorts before widening truth matching.');const lookup=byOperation.find(row=>row.operation==='truth-lookup');if(lookup?.p95DurationMs!==undefined&&lookup.p95DurationMs>100)recommendations.push(`Truth lookup p95 is ${lookup.p95DurationMs.toFixed(0)} ms; profile IndexedDB context indexes and pack overlap.`);if(lookup&&lookup.unknown/lookup.attempts>.25)recommendations.push('More than 25% of truth lookups are Unknown; use P24 acquisition gaps/P19 coverage before changing matcher strictness.');const workspace=byOperation.find(row=>row.operation==='workspace');if(workspace&&(workspace.errors+workspace.conflicts)>0)recommendations.push('Workspace validation/import failures exist; preserve validate-first restore and investigate the top machine reason code.');const sync=byOperation.find(row=>row.operation==='sync');if(sync&&sync.conflicts>0)recommendations.push('Cross-device sync conflicts were observed; do not enable last-write-wins—surface manual reconciliation/export.');
 const quota=rows.filter(event=>event.operation==='storage-quota'&&typeof event.value==='number').sort((a,b)=>b.timestamp-a.timestamp)[0]?.value;if(quota!==undefined&&quota>.8)recommendations.push(`Browser storage quota is ${(quota*100).toFixed(0)}% utilized; export P29 workspace and prune replaceable solver packs before quota exhaustion.`);
 return{windowDays,events:rows.length,byOperation,topReasons,recommendations,latestStorageQuotaRatio:quota,caveats:['Reliability telemetry is local product telemetry only; it contains no raw HH, cards, player names, chat text, tokens or credentials.','Telemetry measures software/data-path reliability, not poker skill or solver truth.','A high Unknown rate should drive P24 truth acquisition, never approximate truth matching.']};
}
