import { RangeBucket, RangeOption, RangeQuestion } from './types';

const SOURCE = {
  trustTier: 'heuristic-estimate' as const,
  label: 'Poker Coach expert teaching baseline',
  disclaimer: '各手牌 Equity 與行動頻率是可審核的教學估計，不是特定 Solver 節點的精確輸出。',
};

const O = (
  hand: string,
  bucket: RangeBucket,
  combos: number,
  heroEquity: number,
  baselineFrequency: number,
): RangeOption => ({ hand, bucket, combos, heroEquity, baselineFrequency });

export const RANGE_QUESTIONS: RangeQuestion[] = [
  {
    id: 'co-shove-aqs',
    title: '18BB CO 直接推進',
    table: '錦標賽 9 人桌',
    stack: '有效 18BB',
    villain: 'CO 一般玩家',
    heroHand: 'A♠ Q♠',
    heroPosition: 'BTN',
    action: ['前位全部 Fold', 'CO 直接 All-In 18BB', '輪到 BTN 決定'],
    potAfterBet: 20.5,
    callCost: 18,
    prompt: '建立 CO 的加權推進範圍，再判斷 AQs 對你所選範圍的實際決策。',
    category: ['對抗範圍', '短碼策略', '翻前'],
    difficulty: '中階',
    options: [
      O('AA', 'monster', 3, 12, 0.2), O('KK', 'monster', 6, 34, 0.25), O('QQ', 'strong', 3, 34, 0.8),
      O('77', 'strong', 6, 46, 1), O('44', 'medium', 6, 48, 1), O('22', 'medium', 6, 49, 0.8),
      O('AJs', 'strong', 3, 73, 1), O('ATo', 'medium', 9, 74, 0.7), O('KQs', 'strong', 3, 70, 1),
      O('K8o', 'air', 12, 68, 0), O('76s', 'draw', 4, 59, 0),
    ],
    explanation: '真正的答案由推進範圍組成決定。中小口袋對與較弱 Ax 越多，AQs 的 Equity 越高；若只剩高口袋對與強 Ax，答案可能反轉成 Fold。',
    blockerNote: 'Hero 持有 A 與 Q，會減少 AA、QQ、AQ 等組合；系統已在各選項的可用 Combo 數中反映這件事。',
    assumptions: ['Chip EV，不計 ICM risk premium', '尚未行動玩家不納入額外碰撞風險'],
    source: SOURCE,
  },
  {
    id: 'fourbet-shove-qq',
    title: 'UTG 40BB 4-Bet Shove',
    table: '6 人桌現金局',
    stack: '有效 40BB',
    villain: 'UTG 一般 TAG',
    heroHand: 'Q♣ Q♦',
    heroPosition: 'BTN',
    action: ['UTG 開到 2.5BB', 'BTN 3-Bet 到 8.5BB', 'UTG All-In 40BB'],
    potAfterBet: 50,
    callCost: 31.5,
    prompt: '調整 UTG 的 4-Bet Shove 權重，觀察 QQ 的 Equity 與 Call EV 如何改變。',
    category: ['對抗範圍', '4-Bet', '翻前'],
    difficulty: '進階',
    options: [
      O('AA', 'monster', 6, 18, 1), O('KK', 'monster', 6, 18, 1), O('QQ', 'strong', 1, 50, 1),
      O('JJ', 'strong', 6, 81, 0.75), O('TT', 'medium', 6, 82, 0.15), O('AKs', 'strong', 4, 54, 1),
      O('AKo', 'strong', 12, 57, 0.75), O('AQs', 'medium', 2, 72, 0), O('A5s', 'air', 4, 70, 0),
      O('99', 'medium', 6, 82, 0),
    ],
    explanation: '不要因為「可能有 AA」就停止分析。QQ 的決策取決於 AA、KK、JJ、AK 與更寬半詐唬各自有多少可用組合與行動頻率。',
    blockerNote: 'Hero 的兩張 Q 把 Villain QQ 降到 1 組，但完全沒有阻擋 AA、KK、AK。',
    assumptions: ['無 rake 的攤牌 Equity 教學模型', '未計算 5-Bet Fold Equity，僅比較 Fold 與 Call'],
    source: SOURCE,
  },
  {
    id: 'flop-cbet-second-pair',
    title: 'K-9-4 面對 33% C-Bet',
    table: '6 人桌現金局',
    stack: '有效 80BB',
    villain: 'BTN 偏積極',
    heroHand: 'A♦ 9♣',
    heroPosition: 'BB',
    board: 'K♠ 9♦ 4♠',
    action: ['BTN 開到 2.3BB', 'BB Call', 'BB Check，BTN 打 33% Pot'],
    potAfterBet: 6.8,
    callCost: 1.7,
    prompt: '用權重描述 BTN 的小尺寸 C-Bet 範圍，判斷第二對是否達到繼續門檻。',
    category: ['對抗範圍', 'C-Bet', '翻後'],
    difficulty: '中階',
    options: [
      O('KK', 'monster', 3, 8, 1), O('99', 'monster', 1, 8, 1), O('AK', 'strong', 9, 15, 1),
      O('KQ', 'strong', 12, 18, 1), O('QQ', 'medium', 6, 78, 0.8), O('TT', 'medium', 6, 80, 0.8),
      O('A♠Q♠', 'draw', 1, 52, 1), O('QJ', 'draw', 16, 74, 0.6), O('A5', 'air', 12, 82, 0.5),
      O('76o', 'air', 12, 88, 0.1),
    ],
    explanation: '小尺寸下注通常保留大量口袋對、聽牌與帶後門的高張。Hero 不需要擊敗價值區，只需要對整個加權下注範圍超過 Pot Odds。',
    blockerNote: 'Hero 沒有黑桃，因此沒有刪除 Villain 的主要同花聽牌；這會影響範圍中的半詐唬密度。',
    assumptions: ['不計 Turn 後續實現率折價', 'AK、KQ、QJ 等未指定花色牌以聚合 Combo 表示'],
    source: SOURCE,
  },
  {
    id: 'turn-checkraise-aq',
    title: 'Turn 面對被動玩家 Check-Raise',
    table: '9 人桌現金局',
    stack: '有效 100BB',
    villain: '偏被動常客',
    heroHand: 'A♠ Q♦',
    heroPosition: 'CO',
    board: 'A♦ 7♣ 2♣ J♠',
    action: ['CO 開池，BB Call', 'Flop：BB Check-Call 40%', 'Turn：Hero Bet 8BB，BB Raise 到 28BB'],
    potAfterBet: 52,
    callCost: 20,
    prompt: '決定價值牌與梅花半詐唬的權重，再測試 AQ 是否能繼續。',
    category: ['對抗範圍', 'Check-Raise', 'Exploit'],
    difficulty: '進階',
    options: [
      O('AJ', 'monster', 6, 7, 1), O('77', 'monster', 3, 9, 1), O('22', 'monster', 3, 9, 1),
      O('A7s', 'monster', 2, 7, 1), O('AT', 'strong', 8, 86, 0), O('88', 'medium', 6, 95, 0),
      O('K♣Q♣', 'draw', 1, 28, 0.35), O('Q♣T♣', 'draw', 1, 30, 0.35), O('6♣5♣', 'draw', 1, 32, 0.35),
      O('65s 無梅花', 'air', 3, 12, 0),
    ],
    explanation: '被動玩家的 Turn Check-Raise 往往價值過重。只有當你賦予足夠的梅花半詐唬權重時，AQ 的 Call EV 才會接近或超過零。',
    blockerNote: 'Q♦ 不會阻擋任何 Q♣X♣。花色必須精確處理，不能只看牌點。',
    assumptions: ['採用實戰 underbluff 基準', '未計算 River 位置與實現率，偏向保守 Exploit'],
    source: SOURCE,
  },
  {
    id: 'river-overbet-kj',
    title: 'River 面對 150% Pot All-In',
    table: '6 人桌現金局',
    stack: '有效 120BB',
    villain: '有能力詐唬的 LAG',
    heroHand: 'K♠ J♦',
    heroPosition: 'BB',
    board: 'Q♥ 8♥ 3♣ 2♠ K♣',
    action: ['BTN 開池，BB Call', 'Flop 與 Turn：BTN 連打，BB 連續 Call', 'River：BTN 打 150% Pot All-In'],
    potAfterBet: 100,
    callCost: 60,
    prompt: '用價值與錯過聽牌的頻率建立極化範圍，測試 KJ 的 Bluff-Catch EV。',
    category: ['對抗範圍', 'Bluff Catch', 'River'],
    difficulty: '進階',
    options: [
      O('KK', 'monster', 1, 0, 1), O('KQ', 'monster', 6, 0, 0.25), O('QQ', 'monster', 3, 0, 0.4),
      O('88', 'monster', 3, 0, 0.25), O('AQ', 'strong', 12, 100, 0), O('QJ', 'medium', 9, 100, 0),
      O('A♥J♥', 'air', 1, 100, 1), O('J♥T♥', 'air', 1, 100, 1), O('T♥9♥', 'air', 1, 100, 1),
      O('99', 'medium', 6, 100, 0),
    ],
    explanation: 'River 已沒有未來牌，Hero Equity 就是 Villain 詐唬的加權比例。選入或移除一個詐唬 Combo，都可能直接跨過 37.5% 的門檻。',
    blockerNote: 'KJ 同時可能阻擋 KQ 價值與 J♥T♥ 詐唬；阻擋價值有利 Call，阻擋詐唬則不利 Call。',
    assumptions: ['River Equity 以贏或輸二元結果估算', '不計 rake'],
    source: SOURCE,
  },
  {
    id: 'multiway-donk-aa',
    title: '多人池面對 75% Donk Bet',
    table: '9 人桌現金局',
    stack: '有效 70BB',
    villain: 'BB 鬆弱玩家',
    heroHand: 'A♠ A♦',
    heroPosition: 'UTG',
    board: '8♣ 7♣ 4♦',
    action: ['UTG 開池，CO Call，BB Call', 'Flop：BB 領打 75% Pot', 'CO 尚未行動'],
    potAfterBet: 17.5,
    callCost: 7.5,
    prompt: '調整成牌、頂對與複合聽牌權重，判斷 AA 是否仍有正 Call EV。',
    category: ['對抗範圍', '多人底池', 'Donk Bet'],
    difficulty: '進階',
    options: [
      O('88', 'monster', 3, 9, 0.7), O('77', 'monster', 3, 9, 0.7), O('44', 'monster', 3, 9, 0.7),
      O('65s', 'monster', 4, 25, 0.8), O('87s', 'monster', 2, 20, 0.8), O('A8', 'strong', 6, 80, 0.6),
      O('9♣6♣', 'draw', 1, 55, 1), O('A♣5♣', 'draw', 1, 60, 1), O('T♣9♣', 'draw', 1, 58, 1),
      O('55', 'medium', 6, 90, 0.2), O('KQ', 'air', 16, 95, 0),
    ],
    explanation: '多人池 Donk 的價值密度通常較高，但若玩家也會用頂對、弱對與複合聽牌領打，AA 對整體範圍仍可能高於跟注門檻。',
    blockerNote: 'Hero 沒有梅花，Villain 的強梅花聽牌完整保留，這通常提高 Call 相對於 Raise 的價值。',
    assumptions: ['僅比較 Fold 與 Call', '未計入 CO 尚未行動造成的多方 Equity 折價'],
    source: SOURCE,
  },
];
