import { HistoryItem, Street } from '../types';

const DAY=86400000;
export interface MonthlyPokerOutcome { month:string; verifiedDecisions:number; averageEvLossBB?:number; alignedRate?:number; frequencyWeightedLeakScoreBB100?:number; byStreet:Partial<Record<Street,{decisions:number;averageEvLossBB:number}>>; }
export interface FamilyOutcome { decisionFamilyId:string; street?:Street; position?:string; observations:number; earlyAverageEvLossBB?:number; recentAverageEvLossBB?:number; observedDeltaBB?:number; improved?:boolean; }
export interface TrainingPrescription { decisionFamilyId:string; street?:Street; position?:string; verifiedObservations:number; averageEvLossBB:number; estimatedFrequencyPer100?:number; recentTrainingAttempts:number; recentTrainingAccuracy?:number; delayedRetention?:number; priority:number; reason:string; }
export interface LongitudinalPokerReport { months:MonthlyPokerOutcome[]; families:FamilyOutcome[]; prescriptions:TrainingPrescription[]; caveats:string[]; }

function verifiedCash(item:HistoryItem){return item.trainingType==='real-hand'&&item.utilityUnit==='bb'&&item.utilityModel==='cash-chip-ev'&&typeof item.utilityLoss==='number'&&Number.isFinite(item.utilityLoss)&&(item.truthTier==='verified-solver'||item.truthTier==='exact-math');}
const mean=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:undefined;
function monthKey(timestamp:number){const d=new Date(timestamp);return`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}

export function buildMonthlyPokerOutcomes(history:HistoryItem[]):MonthlyPokerOutcome[]{
 const groups=new Map<string,HistoryItem[]>();history.filter(verifiedCash).forEach(item=>{const key=monthKey(item.timestamp);const list=groups.get(key)||[];list.push(item);groups.set(key,list);});
 return[...groups.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([month,items])=>{const losses=items.map(item=>Math.max(0,item.utilityLoss||0)),weighted=items.filter(item=>typeof item.spotFrequencyPer100Hands==='number').map(item=>Math.max(0,item.utilityLoss||0)*Math.max(0,item.spotFrequencyPer100Hands||0));const byStreet:MonthlyPokerOutcome['byStreet']={};for(const street of ['Preflop','Flop','Turn','River'] as Street[]){const subset=items.filter(item=>item.street===street);if(subset.length)byStreet[street]={decisions:subset.length,averageEvLossBB:mean(subset.map(item=>Math.max(0,item.utilityLoss||0)))!};}return{month,verifiedDecisions:items.length,averageEvLossBB:mean(losses),alignedRate:items.length?items.filter(item=>Math.max(0,item.utilityLoss||0)<=0.01).length/items.length:undefined,frequencyWeightedLeakScoreBB100:mean(weighted),byStreet};});
}

export function buildFamilyOutcomes(history:HistoryItem[],minimumPerPeriod=5):FamilyOutcome[]{
 const groups=new Map<string,HistoryItem[]>();history.filter(verifiedCash).filter(item=>item.decisionFamilyId).forEach(item=>{const list=groups.get(item.decisionFamilyId!)||[];list.push(item);groups.set(item.decisionFamilyId!,list);});
 return[...groups.entries()].map(([decisionFamilyId,items])=>{items.sort((a,b)=>a.timestamp-b.timestamp);const split=Math.floor(items.length/2),early=items.slice(0,split),recent=items.slice(split),earlyAverageEvLossBB=early.length>=minimumPerPeriod?mean(early.map(i=>i.utilityLoss!)):undefined,recentAverageEvLossBB=recent.length>=minimumPerPeriod?mean(recent.map(i=>i.utilityLoss!)):undefined,delta=earlyAverageEvLossBB!==undefined&&recentAverageEvLossBB!==undefined?recentAverageEvLossBB-earlyAverageEvLossBB:undefined;return{decisionFamilyId,street:items[0]?.street,position:items[0]?.position,observations:items.length,earlyAverageEvLossBB,recentAverageEvLossBB,observedDeltaBB:delta,improved:delta===undefined?undefined:delta<0};}).sort((a,b)=>b.observations-a.observations);
}

export function buildTrainingPrescriptions(history:HistoryItem[],now=Date.now()):TrainingPrescription[]{
 const real=history.filter(verifiedCash).filter(item=>item.decisionFamilyId&&item.timestamp>=now-90*DAY);const groups=new Map<string,HistoryItem[]>();real.forEach(item=>{const list=groups.get(item.decisionFamilyId!)||[];list.push(item);groups.set(item.decisionFamilyId!,list);});const prescriptions:TrainingPrescription[]=[];
 for(const [decisionFamilyId,items] of groups){const losses=items.map(item=>Math.max(0,item.utilityLoss||0)),avgLoss=mean(losses)!;if(avgLoss<=0.005)continue;const freqs=items.map(item=>item.spotFrequencyPer100Hands).filter((v):v is number=>typeof v==='number'&&Number.isFinite(v));const frequency=mean(freqs);const training=history.filter(item=>item.trainingType!=='real-hand'&&item.decisionFamilyId===decisionFamilyId&&item.timestamp>=now-30*DAY);const accuracy=training.length?training.filter(item=>item.correct??item.score>=8).length/training.length:undefined;const delayed=training.filter(item=>item.isDelayedReview),retention=delayed.length?delayed.filter(item=>item.correct??item.score>=8).length/delayed.length:undefined;const repairNeed=1-(retention??accuracy??0.5),confidence=Math.min(1,items.length/10),expectedLoss=avgLoss*(frequency??1),priority=expectedLoss*(0.5+repairNeed)*(0.5+confidence);prescriptions.push({decisionFamilyId,street:items[0].street,position:items[0].position,verifiedObservations:items.length,averageEvLossBB:avgLoss,estimatedFrequencyPer100:frequency,recentTrainingAttempts:training.length,recentTrainingAccuracy:accuracy,delayedRetention:retention,priority,reason:`Verified real-game loss ${avgLoss.toFixed(3)} BB/decision${frequency!==undefined?`, observed frequency signal ${frequency.toFixed(2)}/100`:''}; repair need ${(repairNeed*100).toFixed(0)}%; evidence confidence ${(confidence*100).toFixed(0)}%.`});}
 return prescriptions.sort((a,b)=>b.priority-a.priority);
}

export function buildLongitudinalPokerReport(history:HistoryItem[],now=Date.now()):LongitudinalPokerReport{return{months:buildMonthlyPokerOutcomes(history),families:buildFamilyOutcomes(history),prescriptions:buildTrainingPrescriptions(history,now),caveats:['Monthly and family changes are observational unless separately supported by a preregistered randomized N-of-1 result.','Only verified-solver/exact-math cash BB utility enters real-game regret outcomes; raw HH exposure is excluded.','Frequency-weighted leak score is a comparable signal based on recorded spot-frequency evidence, not a guaranteed bankroll win-rate estimate.']};}
