import { spawn, spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const HOST = '127.0.0.1';
const PREVIEW_PORT = 4173;
const DEBUG_PORT = 9222;
const BASE_URL = `http://${HOST}:${PREVIEW_PORT}/poker-coach-pro/`;
const VITE_BIN = join(process.cwd(), 'node_modules', 'vite', 'bin', 'vite.js');

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
async function waitHttp(url, attempts = 80) { for (let index=0;index<attempts;index+=1){try{const response=await fetch(url);if(response.ok)return response;}catch{}await sleep(125);}throw new Error(`Timed out waiting for ${url}`); }
function commandExists(command){return spawnSync('bash',['-lc',`command -v ${command}`],{stdio:'ignore'}).status===0;}
function browserCommand(){for(const candidate of ['google-chrome','google-chrome-stable','chromium','chromium-browser'])if(commandExists(candidate))return candidate;throw new Error('Chrome/Chromium is required for browser E2E.');}
async function waitForChrome(child,stderr,attempts=160){const url=`http://${HOST}:${DEBUG_PORT}/json/version`;for(let index=0;index<attempts;index+=1){if(child.exitCode!==null)throw new Error(`Chrome exited before CDP was ready (exit=${child.exitCode}). ${stderr().trim()}`);try{const response=await fetch(url);if(response.ok)return response;}catch{}await sleep(125);}throw new Error(`Timed out waiting for ${url}. Chrome exit=${child.exitCode}. ${stderr().trim()}`);}
async function connectCdp(webSocketDebuggerUrl){const socket=new WebSocket(webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});let nextId=1;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(String(event.data));if(!message.id)return;const waiter=pending.get(message.id);if(!waiter)return;pending.delete(message.id);if(message.error)waiter.reject(new Error(message.error.message));else waiter.resolve(message.result);});const send=(method,params={})=>new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});return{socket,send};}
async function evaluate(send,expression,returnByValue=true){const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue});if(result.exceptionDetails)throw new Error(result.exceptionDetails.text||'Runtime.evaluate failed');return result.result?.value;}
async function waitFor(send,expression,description,attempts=140){for(let index=0;index<attempts;index+=1){if(await evaluate(send,expression))return;await sleep(125);}throw new Error(`Timed out waiting for ${description}`);}
async function navigateRoute(send,hash,expectedText){await evaluate(send,`location.hash = ${JSON.stringify(hash)}; true`);await waitFor(send,`!document.querySelector('[data-testid="route-loading"]') && document.body.textContent.includes(${JSON.stringify(expectedText)})`,`${hash||'root'} lazy route: ${expectedText}`);}
async function terminate(child){if(!child||child.exitCode!==null)return;const waitForExit=timeoutMs=>new Promise(resolve=>{if(child.exitCode!==null)return resolve();const timer=setTimeout(resolve,timeoutMs);child.once('exit',()=>{clearTimeout(timer);resolve();});});child.kill('SIGTERM');await waitForExit(1500);if(child.exitCode===null){child.kill('SIGKILL');await waitForExit(1500);}}

const userData=mkdtempSync(join(tmpdir(),'poker-coach-e2e-'));let preview;let chrome;let cdp;let chromeStderr='';
try{
 preview=spawn(process.execPath,[VITE_BIN,'preview','--host',HOST,'--port',String(PREVIEW_PORT)],{stdio:['ignore','pipe','pipe']});await waitHttp(BASE_URL);
 const browser=browserCommand();console.log(`Browser E2E using ${browser}`);chrome=spawn(browser,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage',`--remote-debugging-address=${HOST}`,`--remote-debugging-port=${DEBUG_PORT}`,`--user-data-dir=${userData}`,'--disable-background-networking','--disable-default-apps','--no-first-run','--no-default-browser-check',BASE_URL],{stdio:['ignore','pipe','pipe']});chrome.stderr?.on('data',chunk=>{chromeStderr+=String(chunk);});await waitForChrome(chrome,()=>chromeStderr);
 let pages=[];for(let index=0;index<40;index+=1){pages=await(await fetch(`http://${HOST}:${DEBUG_PORT}/json/list`)).json();if(pages.some(page=>page.type==='page'&&page.webSocketDebuggerUrl))break;await sleep(100);}const page=pages.find(candidate=>candidate.type==='page'&&candidate.webSocketDebuggerUrl);if(!page)throw new Error('No Chrome page target found.');cdp=await connectCdp(page.webSocketDebuggerUrl);await cdp.send('Runtime.enable');await cdp.send('Page.enable');await waitFor(cdp.send,`document.readyState === 'complete'`,'initial page load');await waitFor(cdp.send,`Boolean(document.querySelector('[data-testid="volume-first-home"]'))`,'Infinite Generator Today shell');
 const playerShellText=await evaluate(cdp.send,`document.body.textContent`);if(playerShellText.includes('Hand History')||playerShellText.includes('Truth Ops')||playerShellText.includes('Production Intelligence')||playerShellText.includes('Evidence Ops'))throw new Error('Removed/advanced workbench leaked into primary player shell.');if(playerShellText.includes('你有多確定')||playerShellText.includes('先說你有多確定'))throw new Error('Confidence form leaked into primary player shell.');
 await evaluate(cdp.send,`Array.from(document.querySelectorAll('button')).find(button=>button.textContent?.trim().startsWith('訓練'))?.click(); true`);await waitFor(cdp.send,`Boolean(document.querySelector('[data-testid="volume-training-page"]'))`,'Infinite Generator Train page');await evaluate(cdp.send,`document.querySelector('[data-testid="start-volume-session"]').click(); true`);await waitFor(cdp.send,`Boolean(document.querySelector('[data-testid="infinite-training-table"]'))`,'Infinite Hand Generator table');await waitFor(cdp.send,`Boolean(document.querySelector('[data-testid="decision-action"]') || document.querySelector('[data-testid="solver-action"]'))`,'truth-backed decision action');if(await evaluate(cdp.send,`document.body.textContent.includes('你有多確定') || document.body.textContent.includes('先說你有多確定')`))throw new Error('Infinite decision still asks for confidence.');
 const source=await evaluate(cdp.send,`document.querySelector('[data-testid="infinite-source"]')?.textContent || ''`);if(!source)throw new Error('Infinite generator source provenance missing.');const decisionKind=await evaluate(cdp.send,`document.querySelector('[data-testid="solver-action"]') ? 'solver' : 'scenario'`);if(decisionKind==='solver'){const holeCount=await evaluate(cdp.send,`document.querySelector('[data-testid="solver-hole-cards"]')?.children.length || 0`);if(holeCount!==2)throw new Error(`Solver cards were not rendered as two CardUI nodes (count=${holeCount}).`);}
 const beforeHistory=await evaluate(cdp.send,`JSON.parse(localStorage.getItem('poker_training_history_v6') || '[]').length`);await evaluate(cdp.send,`(document.querySelector('[data-testid="decision-action"]') || document.querySelector('[data-testid="solver-action"]')).click(); true`);await waitFor(cdp.send,`JSON.parse(localStorage.getItem('poker_training_history_v6') || '[]').length > ${beforeHistory}`,'automatic decision persistence');const item=await evaluate(cdp.send,`JSON.parse(localStorage.getItem('poker_training_history_v6') || '[]').at(-1)`);if(!['scenario','solver-corpus'].includes(item.trainingType)||'confidence' in item)throw new Error(`Infinite history contract failed: ${JSON.stringify(item)}`);
 const explanationSelector='[data-testid="decision-explanation"], [data-testid="solver-auto-analysis"]';await waitFor(cdp.send,`Boolean(document.querySelector(${JSON.stringify(explanationSelector)}))`,'post-decision explanation');if(!await evaluate(cdp.send,`Boolean(document.querySelector('[data-testid="advanced-analysis-tools"]'))`))throw new Error('Advanced analysis tools are not discoverable after the decision.');await waitFor(cdp.send,`document.querySelector('[data-testid="advanced-analysis-tools"]')?.dataset.analysisContextReady === 'true'`,'current hand context capture');const contextHref=await evaluate(cdp.send,`document.querySelector('[data-analysis-route="#current-analysis"]')?.getAttribute('href') || ''`);if(!contextHref.startsWith('#current-analysis?ctx='))throw new Error(`Current-hand analysis link did not carry context: ${contextHref}`);await sleep(900);if(!await evaluate(cdp.send,`Boolean(document.querySelector(${JSON.stringify(explanationSelector)}))`))throw new Error(`Explanation auto-advanced away after answer (correct=${item.correct}).`);
 await navigateRoute(cdp.send,contextHref,'Current Hand Analysis');if(!await evaluate(cdp.send,`Boolean(document.querySelector('[data-testid="analysis-context-banner"]'))`))throw new Error('Current-hand analysis lost the captured context.');if(!await evaluate(cdp.send,`document.querySelectorAll('[data-card-code]').length >= 2`))throw new Error('Current-hand analysis did not render the captured cards.');
 await navigateRoute(cdp.send,'#hand-history','Infinite Hand Generator');if(await evaluate(cdp.send,`Boolean(document.querySelector('[data-testid="hand-history-lab"]') || document.querySelector('[data-testid="hh-text"]'))`))throw new Error('Real-game HH route still exists.');await navigateRoute(cdp.send,'#production-intelligence','Infinite Hand Generator');if(await evaluate(cdp.send,`Boolean(document.querySelector('[data-testid="production-intelligence-dashboard"]'))`))throw new Error('Real-game production intelligence route still exists.');
 await navigateRoute(cdp.send,'#truth-ops','Truth Operations');await navigateRoute(cdp.send,'#strategy-surface','Full Strategy Surface');await navigateRoute(cdp.send,'#fgs-workbench','Finite Game Simulation');await navigateRoute(cdp.send,'#experiment','Randomized N-of-1');await evaluate(cdp.send,`document.querySelector('[data-testid="experiment-create"]').click(); true`);await waitFor(cdp.send,`Boolean(localStorage.getItem('poker_learning_experiment_v1'))`,'N-of-1 experiment persistence');await navigateRoute(cdp.send,'','Infinite Hand Generator');
 console.log(`Browser E2E PASS: Infinite Hand Generator (${source}) → truth-backed decision → explanation stays until explicit next → current-hand context bridge → analysis cards preserved → HH/real-game routes absent → training truth tools remain available.`);
}finally{try{cdp?.socket?.close();}catch{}await terminate(chrome);await terminate(preview);try{rmSync(userData,{recursive:true,force:true,maxRetries:10,retryDelay:100});}catch{}}
