import { HistoryItem } from '../types';
import { PostflopAction } from '../strategy-engine-v3';
import { MultiwayTruthStore, multiwayContextKey, verifiedMultiwayRegret } from '../strategy-engine-v4';
import { ParsedHandHistory } from './handHistory';
import { auditHandHistoryForExactGrading } from './handHistoryIntegrity';
import { extractObservedMultiwayDecisions } from './multiwayState';

export interface MultiwayLeakFinding { decisionFamilyId:string; profileKey:string; street:'Flop'|'Turn'|'River'; position:string; chosenAction:PostflopAction; bestAction:PostflopAction; occurrences:number; totalEvLossBB:number; averageEvLossBB:number; sourceReference?:string; }
export interface MultiwayLeakResult { history:HistoryItem[]; findings:MultiwayLeakFinding[]; heroDecisions:number; matchedDecisions:number; gradedDecisions:number; unsupportedDecisions:number; }

export async function buildVerifiedMultiwayLeakEvidence(hands:ParsedHandHistory[],store:MultiwayTruthStore,options:{importedAt?:number;rakePercent?:number;rakeCapBB?:number}={}):Promise<MultiwayLeakResult>{
 const history:HistoryItem[]=[];const grouped=new Map<string,MultiwayLeakFinding>();let heroDecisions=0,matchedDecisions=0;
 for(const hand of hands){const audit=auditHandHistoryForExactGrading(hand);if(!audit.gradeablePostflop)continue;const decisions=extractObservedMultiwayDecisions(hand,options);heroDecisions+=decisions.length;for(const decision of decisions){const node=await store.findExact(decision.query);if(!node)continue;matchedDecisions++;const regret=verifiedMultiwayRegret(node,decision.query.heroCards,decision.chosenAction);if(!regret)continue;const contextFamilyId=multiwayContextKey(node.context),decisionFamilyId=`solver-v4:${node.id}:${regret.combo}`,timestamp=hand.timestamp||options.importedAt||Date.now(),isCash=hand.format==='Cash',facing=(decision.query.toCallBB||0)>0;
  history.push({schemaVersion:6,trainingType:'real-hand',scenarioId:`hh-multiway-grade:${hand.id}:${decision.actionIndex}`,sourceHandId:hand.id,decisionFamilyId,category:['Real Game','Verified Multiway Leak'],score:regret.evLossBB<=0.01?10:Math.max(0,10-regret.evLossBB*5),judgment:regret.evLossBB<=0.01?'solver-aligned':'verified-multiway-regret',timestamp,selectedAction:regret.chosenAction,bestAction:regret.bestAction,correct:regret.evLossBB<=0.01,street:node.context.street,position:node.context.heroPosition.toUpperCase(),chosenEvBB:regret.chosenEvBB,bestEvBB:regret.bestEvBB,evLossBB:regret.evLossBB,truthTier:'verified-solver',truthSourceId:node.id,truthSourceRef:node.source.reference,truthSourceRevision:node.source.solverVersion||node.version,contextFamilyId,evidenceFamilyId:`${hand.format}:${contextFamilyId}`,contextFingerprint:contextFamilyId,skillIds:['postflop.multiway',`postflop.${node.context.street.toLowerCase()}`],situationIds:[`street.${node.context.street.toLowerCase()}`,`position.${node.context.heroPosition}`,`players.${node.context.playersInHand}`,facing?'facing.bet':'checked.to'],gameFormat:hand.format,handsObserved:hands.length,spotExposureCount:1,spotFrequencyPer100Hands:hands.length?100/hands.length:undefined,utilityLoss:isCash?regret.evLossBB:undefined,utilityUnit:isCash?'bb':undefined,utilityModel:isCash?'cash-chip-ev':'priority-only',realGameSource:hand.source,boardTextureId:node.context.board.join(''),notes:`P14 exact multiway grading: ${node.context.playersInHand}-way state matched one verified immutable v4 node. No heads-up fallback.`});
  const current=grouped.get(decisionFamilyId);if(!current)grouped.set(decisionFamilyId,{decisionFamilyId,profileKey:`${node.id}@${node.version}`,street:node.context.street,position:node.context.heroPosition.toUpperCase(),chosenAction:regret.chosenAction,bestAction:regret.bestAction,occurrences:1,totalEvLossBB:regret.evLossBB,averageEvLossBB:regret.evLossBB,sourceReference:node.source.reference});else{current.occurrences++;current.totalEvLossBB+=regret.evLossBB;current.averageEvLossBB=current.totalEvLossBB/current.occurrences;}
 }}
 return{history,findings:[...grouped.values()].sort((a,b)=>b.totalEvLossBB-a.totalEvLossBB||b.occurrences-a.occurrences),heroDecisions,matchedDecisions,gradedDecisions:history.length,unsupportedDecisions:Math.max(0,heroDecisions-matchedDecisions)};
}
