import { Position } from '../strategy-engine-v2/types';
import { PostflopAction, PostflopLineAction, PostflopStreet } from '../strategy-engine-v3';
import { MultiwayTruthQuery } from '../strategy-engine-v4';
import { ParsedHandAction, ParsedHandHistory } from './handHistory';
import { forcedBetContextKey, nonstandardForcedContributionMap, nonstandardForcedStreetCommitmentMap, potStructureContextKey } from './handHistoryGeometry';

export interface ObservedMultiwayDecision { handId:string; actionIndex:number; chosenAction:PostflopAction; query:MultiwayTruthQuery & { street:PostflopStreet; heroCards:string[] } }
const POSITION_MAPS:Record<number,string[]>={2:['BTN','BB'],3:['BTN','SB','BB'],4:['BTN','SB','BB','CO'],5:['BTN','SB','BB','UTG','CO'],6:['BTN','SB','BB','UTG','HJ','CO'],7:['BTN','SB','BB','UTG','MP','HJ','CO'],8:['BTN','SB','BB','UTG','UTG1','MP','HJ','CO'],9:['BTN','SB','BB','UTG','UTG1','UTG2','MP','HJ','CO']};
function positionForPlayer(hand:ParsedHandHistory,name:string):Position|undefined{if(!hand.buttonSeat)return;const seats=[...hand.players].sort((a,b)=>a.seat-b.seat).map(p=>p.seat),player=hand.players.find(p=>p.name===name),bi=seats.indexOf(hand.buttonSeat),pi=player?seats.indexOf(player.seat):-1;if(bi<0||pi<0)return;const label=POSITION_MAPS[Math.min(9,Math.max(2,seats.length))]?.[(pi-bi+seats.length)%seats.length]?.toLowerCase();return label&&['utg','utg1','utg2','mp','hj','co','btn','sb','bb'].includes(label)?label as Position:undefined;}
function kind(a:ParsedHandAction):PostflopAction|undefined{if(a.type==='check'||a.type==='bet'||a.type==='call'||a.type==='raise'||a.type==='fold')return a.type;if(a.type==='all-in')return'allIn';}
function street(value:ParsedHandAction['street']):PostflopStreet|undefined{return value==='Flop'||value==='Turn'||value==='River'?value:undefined;}
const round=(v:number,d=3)=>Math.round(v*10**d)/10**d;
function board(hand:ParsedHandHistory,s:PostflopStreet){return hand.board.slice(0,s==='Flop'?3:s==='Turn'?4:5);}
interface State{street:string;potBB:number;committed:Map<string,number>;total:Map<string,number>;active:Set<string>;preflopLine:PostflopLineAction[];streetLine:PostflopLineAction[];lastAggressorPosition?:Position;}
function added(a:ParsedHandAction,committed:number){if(a.toBB!==undefined&&Number.isFinite(a.toBB))return Math.max(0,a.toBB-committed);return Math.max(0,a.amountBB||0);}
function line(hand:ParsedHandHistory,a:ParsedHandAction,potBefore:number,committed:number):PostflopLineAction|undefined{const actor=positionForPlayer(hand,a.player),action=kind(a);if(!actor||!action||a.type==='post')return;const aggressive=action==='bet'||action==='raise'||action==='allIn';return{actor,action,toBB:a.street==='Preflop'&&a.toBB!==undefined?round(a.toBB):undefined,sizePot:a.street!=='Preflop'&&aggressive&&potBefore>0?round(added(a,committed)/potBefore):undefined};}
function apply(hand:ParsedHandHistory,a:ParsedHandAction,state:State){if(state.street!==a.street){state.street=a.street;state.committed=new Map();state.streetLine=[];}const current=state.committed.get(a.player)||0,potBefore=state.potBB,l=line(hand,a,potBefore,current);if(a.type==='fold')state.active.delete(a.player);if(['post','call','bet','raise','all-in'].includes(a.type)){const x=added(a,current);state.potBB+=x;state.committed.set(a.player,current+x);state.total.set(a.player,(state.total.get(a.player)||0)+x);}if(l){if(a.street==='Preflop')state.preflopLine.push(l);else state.streetLine.push(l);if(l.action==='bet'||l.action==='raise'||l.action==='allIn')state.lastAggressorPosition=l.actor;}}
function remaining(hand:ParsedHandHistory,name:string,state:State){const start=hand.players.find(p=>p.name===name)?.stackBB;return start===undefined?undefined:Math.max(0,start-(state.total.get(name)||0));}

export function extractObservedMultiwayDecisions(hand:ParsedHandHistory,options:{rakePercent?:number;rakeCapBB?:number}={}):ObservedMultiwayDecision[]{
 if(!hand.heroName||!hand.holeCards||hand.holeCards.length!==2||!hand.buttonSeat||(hand.tableSize!==6&&hand.tableSize!==9))return[];const heroPosition=positionForPlayer(hand,hand.heroName);if(!heroPosition)return[];
 const forcedTotal=nonstandardForcedContributionMap(hand),forcedLive=nonstandardForcedStreetCommitmentMap(hand),forcedBetKey=forcedBetContextKey(hand);
 const state:State={street:'Preflop',potBB:[...forcedTotal.values()].reduce((sum,value)=>sum+value,0),committed:new Map(forcedLive),total:new Map(forcedTotal),active:new Set(hand.players.map(p=>p.name)),preflopLine:[],streetLine:[]};const out:ObservedMultiwayDecision[]=[];
 hand.actions.forEach((a,actionIndex)=>{if(state.street!==a.street){state.street=a.street;state.committed=new Map();state.streetLine=[];}const s=street(a.street),chosen=kind(a);if(s&&a.player===hand.heroName&&chosen&&state.active.size>=3){const heroRemaining=remaining(hand,hand.heroName!,state);const heroCommitted=state.committed.get(hand.heroName!)||0,maxCommitted=Math.max(0,...state.committed.values()),toCallBB=Math.max(0,maxCommitted-heroCommitted),cards=board(hand,s);const opponents=[...state.active].filter(name=>name!==hand.heroName).map(name=>{const position=positionForPlayer(hand,name),remainingStackBB=remaining(hand,name,state);return position&&remainingStackBB!==undefined?{position,remainingStackBB:round(remainingStackBB)}:undefined;}).filter((v):v is {position:Position;remainingStackBB:number}=>Boolean(v));
   if(heroRemaining!==undefined&&state.potBB>0&&opponents.length===state.active.size-1&&cards.length===(s==='Flop'?3:s==='Turn'?4:5))out.push({handId:hand.id,actionIndex,chosenAction:chosen,query:{heroCards:[...hand.holeCards!],format:hand.format==='Cash'?'cash':'tournament',tableSize:hand.tableSize===6?'6max':'9max',street:s,heroPosition,heroRemainingStackBB:round(heroRemaining),opponents,playersInHand:state.active.size,potBB:round(state.potBB),spr:round(heroRemaining/state.potBB),toCallBB:round(toCallBB),board:cards,preflopLine:[...state.preflopLine],streetLine:[...state.streetLine],lastAggressorPosition:state.lastAggressorPosition,rakePercent:hand.format==='Cash'?options.rakePercent:undefined,rakeCapBB:hand.format==='Cash'?options.rakeCapBB:undefined,forcedBetKey,potStructureKey:potStructureContextKey(hand,state.total,state.active)}});}
   apply(hand,a,state);});return out;
}
